// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module Compute_BConv_Compute_BConv_Pipeline_Load_Mod (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        out_mod_address0,
        out_mod_ce0,
        out_mod_q0,
        out_k_half_address0,
        out_k_half_ce0,
        out_k_half_q0,
        out_m_barrett_address0,
        out_m_barrett_ce0,
        out_m_barrett_q0,
        p_out,
        p_out_ap_vld,
        p_out1,
        p_out1_ap_vld,
        p_out2,
        p_out2_ap_vld,
        p_out3,
        p_out3_ap_vld,
        p_out4,
        p_out4_ap_vld,
        p_out5,
        p_out5_ap_vld,
        p_out6,
        p_out6_ap_vld,
        p_out7,
        p_out7_ap_vld,
        p_out8,
        p_out8_ap_vld,
        p_out9,
        p_out9_ap_vld,
        mod_p_4_out,
        mod_p_4_out_ap_vld,
        p_out10,
        p_out10_ap_vld,
        mod_p_2_out,
        mod_p_2_out_ap_vld,
        mod_p_1_out,
        mod_p_1_out_ap_vld,
        mod_p_out,
        mod_p_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [2:0] out_mod_address0;
output   out_mod_ce0;
input  [63:0] out_mod_q0;
output  [2:0] out_k_half_address0;
output   out_k_half_ce0;
input  [63:0] out_k_half_q0;
output  [2:0] out_m_barrett_address0;
output   out_m_barrett_ce0;
input  [63:0] out_m_barrett_q0;
output  [63:0] p_out;
output   p_out_ap_vld;
output  [63:0] p_out1;
output   p_out1_ap_vld;
output  [63:0] p_out2;
output   p_out2_ap_vld;
output  [63:0] p_out3;
output   p_out3_ap_vld;
output  [63:0] p_out4;
output   p_out4_ap_vld;
output  [63:0] p_out5;
output   p_out5_ap_vld;
output  [63:0] p_out6;
output   p_out6_ap_vld;
output  [63:0] p_out7;
output   p_out7_ap_vld;
output  [63:0] p_out8;
output   p_out8_ap_vld;
output  [63:0] p_out9;
output   p_out9_ap_vld;
output  [63:0] mod_p_4_out;
output   mod_p_4_out_ap_vld;
output  [63:0] p_out10;
output   p_out10_ap_vld;
output  [63:0] mod_p_2_out;
output   mod_p_2_out_ap_vld;
output  [63:0] mod_p_1_out;
output   mod_p_1_out_ap_vld;
output  [63:0] mod_p_out;
output   mod_p_out_ap_vld;

reg ap_idle;
reg p_out_ap_vld;
reg p_out1_ap_vld;
reg p_out2_ap_vld;
reg p_out3_ap_vld;
reg p_out4_ap_vld;
reg p_out5_ap_vld;
reg p_out6_ap_vld;
reg p_out7_ap_vld;
reg p_out8_ap_vld;
reg p_out9_ap_vld;
reg mod_p_4_out_ap_vld;
reg p_out10_ap_vld;
reg mod_p_2_out_ap_vld;
reg mod_p_1_out_ap_vld;
reg mod_p_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln220_fu_288_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [2:0] p_1_reg_544;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln220_fu_300_p1;
wire    ap_block_pp0_stage0;
reg   [2:0] p_fu_72;
wire   [2:0] add_ln220_fu_294_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_p_1;
reg   [63:0] mod_p_fu_76;
reg   [63:0] mod_p_1_fu_80;
reg   [63:0] mod_p_2_fu_84;
reg   [63:0] empty_fu_88;
reg   [63:0] mod_p_4_fu_92;
reg   [63:0] empty_69_fu_96;
reg   [63:0] empty_70_fu_100;
reg   [63:0] empty_71_fu_104;
reg   [63:0] empty_72_fu_108;
reg   [63:0] empty_73_fu_112;
reg   [63:0] empty_74_fu_116;
reg   [63:0] empty_75_fu_120;
reg   [63:0] empty_76_fu_124;
reg   [63:0] empty_77_fu_128;
reg   [63:0] empty_78_fu_132;
wire    ap_block_pp0_stage0_01001;
reg    out_mod_ce0_local;
reg    out_k_half_ce0_local;
reg    out_m_barrett_ce0_local;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 p_fu_72 = 3'd0;
#0 mod_p_fu_76 = 64'd0;
#0 mod_p_1_fu_80 = 64'd0;
#0 mod_p_2_fu_84 = 64'd0;
#0 empty_fu_88 = 64'd0;
#0 mod_p_4_fu_92 = 64'd0;
#0 empty_69_fu_96 = 64'd0;
#0 empty_70_fu_100 = 64'd0;
#0 empty_71_fu_104 = 64'd0;
#0 empty_72_fu_108 = 64'd0;
#0 empty_73_fu_112 = 64'd0;
#0 empty_74_fu_116 = 64'd0;
#0 empty_75_fu_120 = 64'd0;
#0 empty_76_fu_124 = 64'd0;
#0 empty_77_fu_128 = 64'd0;
#0 empty_78_fu_132 = 64'd0;
#0 ap_done_reg = 1'b0;
end

Compute_BConv_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln220_fu_288_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            p_fu_72 <= add_ln220_fu_294_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            p_fu_72 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((p_1_reg_544 == 3'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_69_fu_96 <= out_k_half_q0;
        empty_70_fu_100 <= out_m_barrett_q0;
        empty_fu_88 <= out_mod_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((p_1_reg_544 == 3'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_71_fu_104 <= out_k_half_q0;
        empty_72_fu_108 <= out_m_barrett_q0;
        mod_p_2_fu_84 <= out_mod_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((p_1_reg_544 == 3'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_73_fu_112 <= out_k_half_q0;
        empty_74_fu_116 <= out_m_barrett_q0;
        mod_p_1_fu_80 <= out_mod_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((p_1_reg_544 == 3'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_75_fu_120 <= out_k_half_q0;
        empty_76_fu_124 <= out_m_barrett_q0;
        mod_p_fu_76 <= out_mod_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((~(p_1_reg_544 == 3'd3) & ~(p_1_reg_544 == 3'd2) & ~(p_1_reg_544 == 3'd1) & ~(p_1_reg_544 == 3'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_77_fu_128 <= out_k_half_q0;
        empty_78_fu_132 <= out_m_barrett_q0;
        mod_p_4_fu_92 <= out_mod_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_1_reg_544 <= ap_sig_allocacmp_p_1;
    end
end

always @ (*) begin
    if (((icmp_ln220_fu_288_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_p_1 = 3'd0;
    end else begin
        ap_sig_allocacmp_p_1 = p_fu_72;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln220_fu_288_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mod_p_1_out_ap_vld = 1'b1;
    end else begin
        mod_p_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln220_fu_288_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mod_p_2_out_ap_vld = 1'b1;
    end else begin
        mod_p_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln220_fu_288_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mod_p_4_out_ap_vld = 1'b1;
    end else begin
        mod_p_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln220_fu_288_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mod_p_out_ap_vld = 1'b1;
    end else begin
        mod_p_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_k_half_ce0_local = 1'b1;
    end else begin
        out_k_half_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_m_barrett_ce0_local = 1'b1;
    end else begin
        out_m_barrett_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_mod_ce0_local = 1'b1;
    end else begin
        out_mod_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln220_fu_288_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out10_ap_vld = 1'b1;
    end else begin
        p_out10_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln220_fu_288_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out1_ap_vld = 1'b1;
    end else begin
        p_out1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln220_fu_288_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out2_ap_vld = 1'b1;
    end else begin
        p_out2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln220_fu_288_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out3_ap_vld = 1'b1;
    end else begin
        p_out3_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln220_fu_288_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out4_ap_vld = 1'b1;
    end else begin
        p_out4_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln220_fu_288_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out5_ap_vld = 1'b1;
    end else begin
        p_out5_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln220_fu_288_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out6_ap_vld = 1'b1;
    end else begin
        p_out6_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln220_fu_288_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out7_ap_vld = 1'b1;
    end else begin
        p_out7_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln220_fu_288_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out8_ap_vld = 1'b1;
    end else begin
        p_out8_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln220_fu_288_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out9_ap_vld = 1'b1;
    end else begin
        p_out9_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln220_fu_288_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out_ap_vld = 1'b1;
    end else begin
        p_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln220_fu_294_p2 = (ap_sig_allocacmp_p_1 + 3'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln220_fu_288_p2 = ((ap_sig_allocacmp_p_1 == 3'd5) ? 1'b1 : 1'b0);

assign mod_p_1_out = mod_p_1_fu_80;

assign mod_p_2_out = mod_p_2_fu_84;

assign mod_p_4_out = mod_p_4_fu_92;

assign mod_p_out = mod_p_fu_76;

assign out_k_half_address0 = zext_ln220_fu_300_p1;

assign out_k_half_ce0 = out_k_half_ce0_local;

assign out_m_barrett_address0 = zext_ln220_fu_300_p1;

assign out_m_barrett_ce0 = out_m_barrett_ce0_local;

assign out_mod_address0 = zext_ln220_fu_300_p1;

assign out_mod_ce0 = out_mod_ce0_local;

assign p_out = empty_78_fu_132;

assign p_out1 = empty_77_fu_128;

assign p_out10 = empty_fu_88;

assign p_out2 = empty_76_fu_124;

assign p_out3 = empty_75_fu_120;

assign p_out4 = empty_74_fu_116;

assign p_out5 = empty_73_fu_112;

assign p_out6 = empty_72_fu_108;

assign p_out7 = empty_71_fu_104;

assign p_out8 = empty_70_fu_100;

assign p_out9 = empty_69_fu_96;

assign zext_ln220_fu_300_p1 = ap_sig_allocacmp_p_1;

endmodule //Compute_BConv_Compute_BConv_Pipeline_Load_Mod
