// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module Top_NTT_Kernel_Pipeline_VITIS_LOOP_96_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        TwiddleIndex_7_address0,
        TwiddleIndex_7_ce0,
        TwiddleIndex_7_we0,
        TwiddleIndex_7_d0,
        TwiddleIndex_6_address0,
        TwiddleIndex_6_ce0,
        TwiddleIndex_6_we0,
        TwiddleIndex_6_d0,
        TwiddleIndex_5_address0,
        TwiddleIndex_5_ce0,
        TwiddleIndex_5_we0,
        TwiddleIndex_5_d0,
        TwiddleIndex_4_address0,
        TwiddleIndex_4_ce0,
        TwiddleIndex_4_we0,
        TwiddleIndex_4_d0,
        TwiddleIndex_3_address0,
        TwiddleIndex_3_ce0,
        TwiddleIndex_3_we0,
        TwiddleIndex_3_d0,
        TwiddleIndex_2_address0,
        TwiddleIndex_2_ce0,
        TwiddleIndex_2_we0,
        TwiddleIndex_2_d0,
        TwiddleIndex_1_address0,
        TwiddleIndex_1_ce0,
        TwiddleIndex_1_we0,
        TwiddleIndex_1_d0,
        TwiddleIndex_address0,
        TwiddleIndex_ce0,
        TwiddleIndex_we0,
        TwiddleIndex_d0,
        zext_ln278,
        cmp_i_i,
        shr_i,
        shl10_i,
        shl_i_cast
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [1:0] TwiddleIndex_7_address0;
output   TwiddleIndex_7_ce0;
output   TwiddleIndex_7_we0;
output  [16:0] TwiddleIndex_7_d0;
output  [1:0] TwiddleIndex_6_address0;
output   TwiddleIndex_6_ce0;
output   TwiddleIndex_6_we0;
output  [16:0] TwiddleIndex_6_d0;
output  [1:0] TwiddleIndex_5_address0;
output   TwiddleIndex_5_ce0;
output   TwiddleIndex_5_we0;
output  [16:0] TwiddleIndex_5_d0;
output  [1:0] TwiddleIndex_4_address0;
output   TwiddleIndex_4_ce0;
output   TwiddleIndex_4_we0;
output  [16:0] TwiddleIndex_4_d0;
output  [1:0] TwiddleIndex_3_address0;
output   TwiddleIndex_3_ce0;
output   TwiddleIndex_3_we0;
output  [16:0] TwiddleIndex_3_d0;
output  [1:0] TwiddleIndex_2_address0;
output   TwiddleIndex_2_ce0;
output   TwiddleIndex_2_we0;
output  [16:0] TwiddleIndex_2_d0;
output  [1:0] TwiddleIndex_1_address0;
output   TwiddleIndex_1_ce0;
output   TwiddleIndex_1_we0;
output  [16:0] TwiddleIndex_1_d0;
output  [1:0] TwiddleIndex_address0;
output   TwiddleIndex_ce0;
output   TwiddleIndex_we0;
output  [16:0] TwiddleIndex_d0;
input  [3:0] zext_ln278;
input  [0:0] cmp_i_i;
input  [5:0] shr_i;
input  [16:0] shl10_i;
input  [11:0] shl_i_cast;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] tmp_fu_256_p3;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] zext_ln96_fu_278_p1;
reg   [5:0] l_7_fu_98;
wire   [5:0] add_ln96_fu_566_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_l;
reg    TwiddleIndex_we0_local;
wire   [16:0] add_ln101_fu_510_p2;
reg    TwiddleIndex_ce0_local;
reg    TwiddleIndex_1_we0_local;
wire   [16:0] add_ln99_fu_517_p2;
reg    TwiddleIndex_1_ce0_local;
reg    TwiddleIndex_2_we0_local;
wire   [16:0] add_ln101_1_fu_524_p2;
reg    TwiddleIndex_2_ce0_local;
reg    TwiddleIndex_3_we0_local;
wire   [16:0] add_ln99_1_fu_531_p2;
reg    TwiddleIndex_3_ce0_local;
reg    TwiddleIndex_4_we0_local;
wire   [16:0] add_ln101_2_fu_538_p2;
reg    TwiddleIndex_4_ce0_local;
reg    TwiddleIndex_5_we0_local;
wire   [16:0] add_ln99_2_fu_545_p2;
reg    TwiddleIndex_5_ce0_local;
reg    TwiddleIndex_6_we0_local;
wire   [16:0] add_ln101_3_fu_552_p2;
reg    TwiddleIndex_6_ce0_local;
reg    TwiddleIndex_7_we0_local;
wire   [16:0] add_ln99_3_fu_559_p2;
reg    TwiddleIndex_7_ce0_local;
wire   [1:0] lshr_ln7_fu_268_p4;
wire   [4:0] trunc_ln96_fu_264_p1;
wire   [11:0] zext_ln99_fu_290_p1;
wire   [11:0] zext_ln278_cast_fu_240_p1;
wire   [11:0] lshr_ln99_fu_294_p2;
wire   [3:0] tmp_s_fu_304_p4;
wire   [4:0] or_ln4_fu_314_p3;
wire   [11:0] zext_ln101_fu_322_p1;
wire   [11:0] lshr_ln101_fu_326_p2;
wire   [2:0] tmp_1543_fu_336_p4;
wire   [4:0] or_ln101_1_fu_346_p3;
wire   [11:0] zext_ln101_2_fu_354_p1;
wire   [11:0] lshr_ln101_1_fu_358_p2;
wire   [4:0] or_ln101_2_fu_368_p3;
wire   [11:0] zext_ln101_4_fu_376_p1;
wire   [11:0] lshr_ln101_2_fu_380_p2;
wire   [4:0] or_ln101_3_fu_390_p3;
wire   [11:0] zext_ln101_6_fu_398_p1;
wire   [11:0] lshr_ln101_3_fu_402_p2;
wire   [0:0] tmp_2564_fu_412_p3;
wire   [4:0] or_ln101_4_fu_420_p5;
wire   [11:0] zext_ln101_8_fu_432_p1;
wire   [11:0] lshr_ln101_4_fu_436_p2;
wire   [4:0] or_ln101_5_fu_446_p3;
wire   [11:0] zext_ln101_10_fu_454_p1;
wire   [11:0] lshr_ln101_5_fu_458_p2;
wire   [4:0] or_ln101_6_fu_468_p3;
wire   [11:0] zext_ln101_12_fu_476_p1;
wire   [11:0] lshr_ln101_6_fu_480_p2;
wire   [16:0] shr_i_cast_fu_244_p1;
wire   [16:0] select_ln98_fu_490_p3;
wire   [16:0] add_ln98_1_fu_498_p2;
wire   [16:0] shl_i_cast_cast_fu_236_p1;
wire   [16:0] zext_ln99_1_fu_300_p1;
wire   [16:0] add_ln98_fu_504_p2;
wire   [16:0] zext_ln101_1_fu_332_p1;
wire   [16:0] zext_ln101_3_fu_364_p1;
wire   [16:0] zext_ln101_5_fu_386_p1;
wire   [16:0] zext_ln101_7_fu_408_p1;
wire   [16:0] zext_ln101_9_fu_442_p1;
wire   [16:0] zext_ln101_11_fu_464_p1;
wire   [16:0] zext_ln101_13_fu_486_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 l_7_fu_98 = 6'd0;
#0 ap_done_reg = 1'b0;
end

Top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((tmp_fu_256_p3 == 1'd0)) begin
            l_7_fu_98 <= add_ln96_fu_566_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            l_7_fu_98 <= 6'd0;
        end
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        TwiddleIndex_1_ce0_local = 1'b1;
    end else begin
        TwiddleIndex_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_256_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        TwiddleIndex_1_we0_local = 1'b1;
    end else begin
        TwiddleIndex_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        TwiddleIndex_2_ce0_local = 1'b1;
    end else begin
        TwiddleIndex_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_256_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        TwiddleIndex_2_we0_local = 1'b1;
    end else begin
        TwiddleIndex_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        TwiddleIndex_3_ce0_local = 1'b1;
    end else begin
        TwiddleIndex_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_256_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        TwiddleIndex_3_we0_local = 1'b1;
    end else begin
        TwiddleIndex_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        TwiddleIndex_4_ce0_local = 1'b1;
    end else begin
        TwiddleIndex_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_256_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        TwiddleIndex_4_we0_local = 1'b1;
    end else begin
        TwiddleIndex_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        TwiddleIndex_5_ce0_local = 1'b1;
    end else begin
        TwiddleIndex_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_256_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        TwiddleIndex_5_we0_local = 1'b1;
    end else begin
        TwiddleIndex_5_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        TwiddleIndex_6_ce0_local = 1'b1;
    end else begin
        TwiddleIndex_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_256_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        TwiddleIndex_6_we0_local = 1'b1;
    end else begin
        TwiddleIndex_6_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        TwiddleIndex_7_ce0_local = 1'b1;
    end else begin
        TwiddleIndex_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_256_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        TwiddleIndex_7_we0_local = 1'b1;
    end else begin
        TwiddleIndex_7_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        TwiddleIndex_ce0_local = 1'b1;
    end else begin
        TwiddleIndex_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_256_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        TwiddleIndex_we0_local = 1'b1;
    end else begin
        TwiddleIndex_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_256_p3 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_l = 6'd0;
    end else begin
        ap_sig_allocacmp_l = l_7_fu_98;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign TwiddleIndex_1_address0 = zext_ln96_fu_278_p1;

assign TwiddleIndex_1_ce0 = TwiddleIndex_1_ce0_local;

assign TwiddleIndex_1_d0 = add_ln99_fu_517_p2;

assign TwiddleIndex_1_we0 = TwiddleIndex_1_we0_local;

assign TwiddleIndex_2_address0 = zext_ln96_fu_278_p1;

assign TwiddleIndex_2_ce0 = TwiddleIndex_2_ce0_local;

assign TwiddleIndex_2_d0 = add_ln101_1_fu_524_p2;

assign TwiddleIndex_2_we0 = TwiddleIndex_2_we0_local;

assign TwiddleIndex_3_address0 = zext_ln96_fu_278_p1;

assign TwiddleIndex_3_ce0 = TwiddleIndex_3_ce0_local;

assign TwiddleIndex_3_d0 = add_ln99_1_fu_531_p2;

assign TwiddleIndex_3_we0 = TwiddleIndex_3_we0_local;

assign TwiddleIndex_4_address0 = zext_ln96_fu_278_p1;

assign TwiddleIndex_4_ce0 = TwiddleIndex_4_ce0_local;

assign TwiddleIndex_4_d0 = add_ln101_2_fu_538_p2;

assign TwiddleIndex_4_we0 = TwiddleIndex_4_we0_local;

assign TwiddleIndex_5_address0 = zext_ln96_fu_278_p1;

assign TwiddleIndex_5_ce0 = TwiddleIndex_5_ce0_local;

assign TwiddleIndex_5_d0 = add_ln99_2_fu_545_p2;

assign TwiddleIndex_5_we0 = TwiddleIndex_5_we0_local;

assign TwiddleIndex_6_address0 = zext_ln96_fu_278_p1;

assign TwiddleIndex_6_ce0 = TwiddleIndex_6_ce0_local;

assign TwiddleIndex_6_d0 = add_ln101_3_fu_552_p2;

assign TwiddleIndex_6_we0 = TwiddleIndex_6_we0_local;

assign TwiddleIndex_7_address0 = zext_ln96_fu_278_p1;

assign TwiddleIndex_7_ce0 = TwiddleIndex_7_ce0_local;

assign TwiddleIndex_7_d0 = add_ln99_3_fu_559_p2;

assign TwiddleIndex_7_we0 = TwiddleIndex_7_we0_local;

assign TwiddleIndex_address0 = zext_ln96_fu_278_p1;

assign TwiddleIndex_ce0 = TwiddleIndex_ce0_local;

assign TwiddleIndex_d0 = add_ln101_fu_510_p2;

assign TwiddleIndex_we0 = TwiddleIndex_we0_local;

assign add_ln101_1_fu_524_p2 = (zext_ln101_3_fu_364_p1 + add_ln98_fu_504_p2);

assign add_ln101_2_fu_538_p2 = (zext_ln101_7_fu_408_p1 + add_ln98_fu_504_p2);

assign add_ln101_3_fu_552_p2 = (zext_ln101_11_fu_464_p1 + add_ln98_fu_504_p2);

assign add_ln101_fu_510_p2 = (zext_ln99_1_fu_300_p1 + add_ln98_fu_504_p2);

assign add_ln96_fu_566_p2 = (ap_sig_allocacmp_l + 6'd8);

assign add_ln98_1_fu_498_p2 = ($signed(select_ln98_fu_490_p3) + $signed(17'd131071));

assign add_ln98_fu_504_p2 = (add_ln98_1_fu_498_p2 + shl_i_cast_cast_fu_236_p1);

assign add_ln99_1_fu_531_p2 = (zext_ln101_5_fu_386_p1 + add_ln98_fu_504_p2);

assign add_ln99_2_fu_545_p2 = (zext_ln101_9_fu_442_p1 + add_ln98_fu_504_p2);

assign add_ln99_3_fu_559_p2 = (zext_ln101_13_fu_486_p1 + add_ln98_fu_504_p2);

assign add_ln99_fu_517_p2 = (zext_ln101_1_fu_332_p1 + add_ln98_fu_504_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign lshr_ln101_1_fu_358_p2 = zext_ln101_2_fu_354_p1 >> zext_ln278_cast_fu_240_p1;

assign lshr_ln101_2_fu_380_p2 = zext_ln101_4_fu_376_p1 >> zext_ln278_cast_fu_240_p1;

assign lshr_ln101_3_fu_402_p2 = zext_ln101_6_fu_398_p1 >> zext_ln278_cast_fu_240_p1;

assign lshr_ln101_4_fu_436_p2 = zext_ln101_8_fu_432_p1 >> zext_ln278_cast_fu_240_p1;

assign lshr_ln101_5_fu_458_p2 = zext_ln101_10_fu_454_p1 >> zext_ln278_cast_fu_240_p1;

assign lshr_ln101_6_fu_480_p2 = zext_ln101_12_fu_476_p1 >> zext_ln278_cast_fu_240_p1;

assign lshr_ln101_fu_326_p2 = zext_ln101_fu_322_p1 >> zext_ln278_cast_fu_240_p1;

assign lshr_ln7_fu_268_p4 = {{ap_sig_allocacmp_l[4:3]}};

assign lshr_ln99_fu_294_p2 = zext_ln99_fu_290_p1 >> zext_ln278_cast_fu_240_p1;

assign or_ln101_1_fu_346_p3 = {{tmp_1543_fu_336_p4}, {2'd2}};

assign or_ln101_2_fu_368_p3 = {{tmp_1543_fu_336_p4}, {2'd3}};

assign or_ln101_3_fu_390_p3 = {{lshr_ln7_fu_268_p4}, {3'd4}};

assign or_ln101_4_fu_420_p5 = {{{{lshr_ln7_fu_268_p4}, {1'd1}}, {tmp_2564_fu_412_p3}}, {1'd1}};

assign or_ln101_5_fu_446_p3 = {{lshr_ln7_fu_268_p4}, {3'd6}};

assign or_ln101_6_fu_468_p3 = {{lshr_ln7_fu_268_p4}, {3'd7}};

assign or_ln4_fu_314_p3 = {{tmp_s_fu_304_p4}, {1'd1}};

assign select_ln98_fu_490_p3 = ((cmp_i_i[0:0] == 1'b1) ? shr_i_cast_fu_244_p1 : shl10_i);

assign shl_i_cast_cast_fu_236_p1 = shl_i_cast;

assign shr_i_cast_fu_244_p1 = shr_i;

assign tmp_1543_fu_336_p4 = {{ap_sig_allocacmp_l[4:2]}};

assign tmp_2564_fu_412_p3 = ap_sig_allocacmp_l[32'd1];

assign tmp_fu_256_p3 = ap_sig_allocacmp_l[32'd5];

assign tmp_s_fu_304_p4 = {{ap_sig_allocacmp_l[4:1]}};

assign trunc_ln96_fu_264_p1 = ap_sig_allocacmp_l[4:0];

assign zext_ln101_10_fu_454_p1 = or_ln101_5_fu_446_p3;

assign zext_ln101_11_fu_464_p1 = lshr_ln101_5_fu_458_p2;

assign zext_ln101_12_fu_476_p1 = or_ln101_6_fu_468_p3;

assign zext_ln101_13_fu_486_p1 = lshr_ln101_6_fu_480_p2;

assign zext_ln101_1_fu_332_p1 = lshr_ln101_fu_326_p2;

assign zext_ln101_2_fu_354_p1 = or_ln101_1_fu_346_p3;

assign zext_ln101_3_fu_364_p1 = lshr_ln101_1_fu_358_p2;

assign zext_ln101_4_fu_376_p1 = or_ln101_2_fu_368_p3;

assign zext_ln101_5_fu_386_p1 = lshr_ln101_2_fu_380_p2;

assign zext_ln101_6_fu_398_p1 = or_ln101_3_fu_390_p3;

assign zext_ln101_7_fu_408_p1 = lshr_ln101_3_fu_402_p2;

assign zext_ln101_8_fu_432_p1 = or_ln101_4_fu_420_p5;

assign zext_ln101_9_fu_442_p1 = lshr_ln101_4_fu_436_p2;

assign zext_ln101_fu_322_p1 = or_ln4_fu_314_p3;

assign zext_ln278_cast_fu_240_p1 = zext_ln278;

assign zext_ln96_fu_278_p1 = lshr_ln7_fu_268_p4;

assign zext_ln99_1_fu_300_p1 = lshr_ln99_fu_294_p2;

assign zext_ln99_fu_290_p1 = trunc_ln96_fu_264_p1;

endmodule //Top_NTT_Kernel_Pipeline_VITIS_LOOP_96_1
