// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module Top_Top_Pipeline_init_INTTTwiddle_Loop_VITIS_LOOP_108_3_VITIS_LOOP_109_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RFIFONUM,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        mem_in2,
        p_ZL17INTTTwiddleFactor_0_address0,
        p_ZL17INTTTwiddleFactor_0_ce0,
        p_ZL17INTTTwiddleFactor_0_we0,
        p_ZL17INTTTwiddleFactor_0_d0,
        p_ZL17INTTTwiddleFactor_1_address0,
        p_ZL17INTTTwiddleFactor_1_ce0,
        p_ZL17INTTTwiddleFactor_1_we0,
        p_ZL17INTTTwiddleFactor_1_d0,
        p_ZL17INTTTwiddleFactor_2_address0,
        p_ZL17INTTTwiddleFactor_2_ce0,
        p_ZL17INTTTwiddleFactor_2_we0,
        p_ZL17INTTTwiddleFactor_2_d0,
        p_ZL17INTTTwiddleFactor_3_address0,
        p_ZL17INTTTwiddleFactor_3_ce0,
        p_ZL17INTTTwiddleFactor_3_we0,
        p_ZL17INTTTwiddleFactor_3_d0,
        p_ZL17INTTTwiddleFactor_4_address0,
        p_ZL17INTTTwiddleFactor_4_ce0,
        p_ZL17INTTTwiddleFactor_4_we0,
        p_ZL17INTTTwiddleFactor_4_d0,
        p_ZL17INTTTwiddleFactor_5_address0,
        p_ZL17INTTTwiddleFactor_5_ce0,
        p_ZL17INTTTwiddleFactor_5_we0,
        p_ZL17INTTTwiddleFactor_5_d0,
        p_ZL17INTTTwiddleFactor_6_address0,
        p_ZL17INTTTwiddleFactor_6_ce0,
        p_ZL17INTTTwiddleFactor_6_we0,
        p_ZL17INTTTwiddleFactor_6_d0,
        p_ZL17INTTTwiddleFactor_7_address0,
        p_ZL17INTTTwiddleFactor_7_ce0,
        p_ZL17INTTTwiddleFactor_7_we0,
        p_ZL17INTTTwiddleFactor_7_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [63:0] m_axi_gmem1_AWADDR;
output  [0:0] m_axi_gmem1_AWID;
output  [31:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [0:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [63:0] m_axi_gmem1_WDATA;
output  [7:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [0:0] m_axi_gmem1_WID;
output  [0:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [63:0] m_axi_gmem1_ARADDR;
output  [0:0] m_axi_gmem1_ARID;
output  [31:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [0:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [63:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [0:0] m_axi_gmem1_RID;
input  [8:0] m_axi_gmem1_RFIFONUM;
input  [0:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [0:0] m_axi_gmem1_BID;
input  [0:0] m_axi_gmem1_BUSER;
input  [63:0] mem_in2;
output  [16:0] p_ZL17INTTTwiddleFactor_0_address0;
output   p_ZL17INTTTwiddleFactor_0_ce0;
output   p_ZL17INTTTwiddleFactor_0_we0;
output  [63:0] p_ZL17INTTTwiddleFactor_0_d0;
output  [16:0] p_ZL17INTTTwiddleFactor_1_address0;
output   p_ZL17INTTTwiddleFactor_1_ce0;
output   p_ZL17INTTTwiddleFactor_1_we0;
output  [63:0] p_ZL17INTTTwiddleFactor_1_d0;
output  [16:0] p_ZL17INTTTwiddleFactor_2_address0;
output   p_ZL17INTTTwiddleFactor_2_ce0;
output   p_ZL17INTTTwiddleFactor_2_we0;
output  [63:0] p_ZL17INTTTwiddleFactor_2_d0;
output  [16:0] p_ZL17INTTTwiddleFactor_3_address0;
output   p_ZL17INTTTwiddleFactor_3_ce0;
output   p_ZL17INTTTwiddleFactor_3_we0;
output  [63:0] p_ZL17INTTTwiddleFactor_3_d0;
output  [16:0] p_ZL17INTTTwiddleFactor_4_address0;
output   p_ZL17INTTTwiddleFactor_4_ce0;
output   p_ZL17INTTTwiddleFactor_4_we0;
output  [63:0] p_ZL17INTTTwiddleFactor_4_d0;
output  [16:0] p_ZL17INTTTwiddleFactor_5_address0;
output   p_ZL17INTTTwiddleFactor_5_ce0;
output   p_ZL17INTTTwiddleFactor_5_we0;
output  [63:0] p_ZL17INTTTwiddleFactor_5_d0;
output  [16:0] p_ZL17INTTTwiddleFactor_6_address0;
output   p_ZL17INTTTwiddleFactor_6_ce0;
output   p_ZL17INTTTwiddleFactor_6_we0;
output  [63:0] p_ZL17INTTTwiddleFactor_6_d0;
output  [16:0] p_ZL17INTTTwiddleFactor_7_address0;
output   p_ZL17INTTTwiddleFactor_7_ce0;
output   p_ZL17INTTTwiddleFactor_7_we0;
output  [63:0] p_ZL17INTTTwiddleFactor_7_d0;

reg ap_idle;
reg m_axi_gmem1_ARVALID;
reg m_axi_gmem1_RREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_idle_pp0;
reg   [0:0] first_iter_2_reg_577;
reg    ap_block_state3_io;
reg    ap_block_state11_pp0_stage0_iter10;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln106_fu_289_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem1_blk_n_R;
wire    ap_block_pp0_stage0;
reg    gmem1_blk_n_AR;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln108_fu_313_p2;
reg   [0:0] icmp_ln108_reg_557;
wire   [0:0] and_ln106_fu_331_p2;
reg   [0:0] and_ln106_reg_562;
wire   [2:0] select_ln106_1_fu_337_p3;
reg   [2:0] select_ln106_1_reg_567;
wire   [12:0] t_1_mid2_fu_351_p3;
reg   [12:0] t_1_mid2_reg_572;
wire   [0:0] first_iter_2_fu_359_p2;
reg   [60:0] p_cast2_reg_581;
wire   [2:0] trunc_ln108_fu_465_p1;
reg   [2:0] trunc_ln108_reg_592;
reg   [2:0] trunc_ln108_reg_592_pp0_iter3_reg;
reg   [2:0] trunc_ln108_reg_592_pp0_iter4_reg;
reg   [2:0] trunc_ln108_reg_592_pp0_iter5_reg;
reg   [2:0] trunc_ln108_reg_592_pp0_iter6_reg;
reg   [2:0] trunc_ln108_reg_592_pp0_iter7_reg;
reg   [2:0] trunc_ln108_reg_592_pp0_iter8_reg;
reg   [2:0] trunc_ln108_reg_592_pp0_iter9_reg;
reg   [2:0] trunc_ln108_reg_592_pp0_iter10_reg;
wire   [16:0] add_ln110_fu_491_p2;
reg   [16:0] add_ln110_reg_596;
reg   [16:0] add_ln110_reg_596_pp0_iter3_reg;
reg   [16:0] add_ln110_reg_596_pp0_iter4_reg;
reg   [16:0] add_ln110_reg_596_pp0_iter5_reg;
reg   [16:0] add_ln110_reg_596_pp0_iter6_reg;
reg   [16:0] add_ln110_reg_596_pp0_iter7_reg;
reg   [16:0] add_ln110_reg_596_pp0_iter8_reg;
reg   [16:0] add_ln110_reg_596_pp0_iter9_reg;
reg   [16:0] add_ln110_reg_596_pp0_iter10_reg;
reg   [63:0] gmem1_addr_read_reg_601;
wire   [63:0] zext_ln110_1_fu_502_p1;
wire  signed [63:0] p_cast2_cast_fu_455_p1;
reg   [12:0] t_fu_116;
wire   [12:0] add_ln109_fu_392_p2;
wire    ap_loop_init;
reg   [5:0] b_fu_120;
wire   [5:0] select_ln108_fu_448_p3;
reg   [18:0] indvar_flatten19_fu_124;
wire   [18:0] select_ln108_1_fu_404_p3;
reg   [2:0] l_fu_128;
reg   [19:0] indvar_flatten32_fu_132;
wire   [19:0] add_ln106_2_fu_295_p2;
reg    p_ZL17INTTTwiddleFactor_6_we0_local;
reg    p_ZL17INTTTwiddleFactor_6_ce0_local;
reg    p_ZL17INTTTwiddleFactor_5_we0_local;
reg    p_ZL17INTTTwiddleFactor_5_ce0_local;
reg    p_ZL17INTTTwiddleFactor_4_we0_local;
reg    p_ZL17INTTTwiddleFactor_4_ce0_local;
reg    p_ZL17INTTTwiddleFactor_3_we0_local;
reg    p_ZL17INTTTwiddleFactor_3_ce0_local;
reg    p_ZL17INTTTwiddleFactor_2_we0_local;
reg    p_ZL17INTTTwiddleFactor_2_ce0_local;
reg    p_ZL17INTTTwiddleFactor_1_we0_local;
reg    p_ZL17INTTTwiddleFactor_1_ce0_local;
reg    p_ZL17INTTTwiddleFactor_0_we0_local;
reg    p_ZL17INTTTwiddleFactor_0_ce0_local;
reg    p_ZL17INTTTwiddleFactor_7_we0_local;
reg    p_ZL17INTTTwiddleFactor_7_ce0_local;
wire   [0:0] icmp_ln109_fu_325_p2;
wire   [0:0] xor_ln106_fu_319_p2;
wire   [2:0] add_ln106_1_fu_307_p2;
wire   [0:0] empty_2312_fu_345_p2;
wire   [17:0] or_ln1_fu_365_p3;
wire   [63:0] zext_ln106_fu_373_p1;
wire   [63:0] add_ln106_fu_377_p2;
wire   [18:0] add_ln108_1_fu_398_p2;
wire   [5:0] select_ln106_fu_435_p3;
wire   [5:0] add_ln108_fu_442_p2;
wire   [1:0] lshr_ln2_fu_469_p4;
wire   [16:0] tmp_s_fu_479_p4;
wire   [16:0] zext_ln110_fu_488_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 t_fu_116 = 13'd0;
#0 b_fu_120 = 6'd0;
#0 indvar_flatten19_fu_124 = 19'd0;
#0 l_fu_128 = 3'd0;
#0 indvar_flatten32_fu_132 = 20'd0;
#0 ap_done_reg = 1'b0;
end

Top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter10_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            b_fu_120 <= 6'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            b_fu_120 <= select_ln108_fu_448_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten19_fu_124 <= 19'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln106_fu_289_p2 == 1'd0))) begin
            indvar_flatten19_fu_124 <= select_ln108_1_fu_404_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten32_fu_132 <= 20'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln106_fu_289_p2 == 1'd0))) begin
            indvar_flatten32_fu_132 <= add_ln106_2_fu_295_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            l_fu_128 <= 3'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln106_fu_289_p2 == 1'd0))) begin
            l_fu_128 <= select_ln106_1_fu_337_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            t_fu_116 <= 13'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln106_fu_289_p2 == 1'd0))) begin
            t_fu_116 <= add_ln109_fu_392_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln110_reg_596 <= add_ln110_fu_491_p2;
        add_ln110_reg_596_pp0_iter10_reg <= add_ln110_reg_596_pp0_iter9_reg;
        add_ln110_reg_596_pp0_iter3_reg <= add_ln110_reg_596;
        add_ln110_reg_596_pp0_iter4_reg <= add_ln110_reg_596_pp0_iter3_reg;
        add_ln110_reg_596_pp0_iter5_reg <= add_ln110_reg_596_pp0_iter4_reg;
        add_ln110_reg_596_pp0_iter6_reg <= add_ln110_reg_596_pp0_iter5_reg;
        add_ln110_reg_596_pp0_iter7_reg <= add_ln110_reg_596_pp0_iter6_reg;
        add_ln110_reg_596_pp0_iter8_reg <= add_ln110_reg_596_pp0_iter7_reg;
        add_ln110_reg_596_pp0_iter9_reg <= add_ln110_reg_596_pp0_iter8_reg;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        gmem1_addr_read_reg_601 <= m_axi_gmem1_RDATA;
        trunc_ln108_reg_592 <= trunc_ln108_fu_465_p1;
        trunc_ln108_reg_592_pp0_iter10_reg <= trunc_ln108_reg_592_pp0_iter9_reg;
        trunc_ln108_reg_592_pp0_iter3_reg <= trunc_ln108_reg_592;
        trunc_ln108_reg_592_pp0_iter4_reg <= trunc_ln108_reg_592_pp0_iter3_reg;
        trunc_ln108_reg_592_pp0_iter5_reg <= trunc_ln108_reg_592_pp0_iter4_reg;
        trunc_ln108_reg_592_pp0_iter6_reg <= trunc_ln108_reg_592_pp0_iter5_reg;
        trunc_ln108_reg_592_pp0_iter7_reg <= trunc_ln108_reg_592_pp0_iter6_reg;
        trunc_ln108_reg_592_pp0_iter8_reg <= trunc_ln108_reg_592_pp0_iter7_reg;
        trunc_ln108_reg_592_pp0_iter9_reg <= trunc_ln108_reg_592_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        and_ln106_reg_562 <= and_ln106_fu_331_p2;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        first_iter_2_reg_577 <= first_iter_2_fu_359_p2;
        icmp_ln108_reg_557 <= icmp_ln108_fu_313_p2;
        p_cast2_reg_581 <= {{add_ln106_fu_377_p2[63:3]}};
        select_ln106_1_reg_567 <= select_ln106_1_fu_337_p3;
        t_1_mid2_reg_572 <= t_1_mid2_fu_351_p3;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln106_fu_289_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter10_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (first_iter_2_reg_577 == 1'd1))) begin
        gmem1_blk_n_AR = m_axi_gmem1_ARREADY;
    end else begin
        gmem1_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem1_blk_n_R = m_axi_gmem1_RVALID;
    end else begin
        gmem1_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (first_iter_2_reg_577 == 1'd1))) begin
        m_axi_gmem1_ARVALID = 1'b1;
    end else begin
        m_axi_gmem1_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem1_RREADY = 1'b1;
    end else begin
        m_axi_gmem1_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZL17INTTTwiddleFactor_0_ce0_local = 1'b1;
    end else begin
        p_ZL17INTTTwiddleFactor_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (trunc_ln108_reg_592_pp0_iter10_reg == 3'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZL17INTTTwiddleFactor_0_we0_local = 1'b1;
    end else begin
        p_ZL17INTTTwiddleFactor_0_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZL17INTTTwiddleFactor_1_ce0_local = 1'b1;
    end else begin
        p_ZL17INTTTwiddleFactor_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (trunc_ln108_reg_592_pp0_iter10_reg == 3'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZL17INTTTwiddleFactor_1_we0_local = 1'b1;
    end else begin
        p_ZL17INTTTwiddleFactor_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZL17INTTTwiddleFactor_2_ce0_local = 1'b1;
    end else begin
        p_ZL17INTTTwiddleFactor_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (trunc_ln108_reg_592_pp0_iter10_reg == 3'd2) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZL17INTTTwiddleFactor_2_we0_local = 1'b1;
    end else begin
        p_ZL17INTTTwiddleFactor_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZL17INTTTwiddleFactor_3_ce0_local = 1'b1;
    end else begin
        p_ZL17INTTTwiddleFactor_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (trunc_ln108_reg_592_pp0_iter10_reg == 3'd3) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZL17INTTTwiddleFactor_3_we0_local = 1'b1;
    end else begin
        p_ZL17INTTTwiddleFactor_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZL17INTTTwiddleFactor_4_ce0_local = 1'b1;
    end else begin
        p_ZL17INTTTwiddleFactor_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (trunc_ln108_reg_592_pp0_iter10_reg == 3'd4) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZL17INTTTwiddleFactor_4_we0_local = 1'b1;
    end else begin
        p_ZL17INTTTwiddleFactor_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZL17INTTTwiddleFactor_5_ce0_local = 1'b1;
    end else begin
        p_ZL17INTTTwiddleFactor_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (trunc_ln108_reg_592_pp0_iter10_reg == 3'd5) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZL17INTTTwiddleFactor_5_we0_local = 1'b1;
    end else begin
        p_ZL17INTTTwiddleFactor_5_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZL17INTTTwiddleFactor_6_ce0_local = 1'b1;
    end else begin
        p_ZL17INTTTwiddleFactor_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (trunc_ln108_reg_592_pp0_iter10_reg == 3'd6) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZL17INTTTwiddleFactor_6_we0_local = 1'b1;
    end else begin
        p_ZL17INTTTwiddleFactor_6_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZL17INTTTwiddleFactor_7_ce0_local = 1'b1;
    end else begin
        p_ZL17INTTTwiddleFactor_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (trunc_ln108_reg_592_pp0_iter10_reg == 3'd7) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZL17INTTTwiddleFactor_7_we0_local = 1'b1;
    end else begin
        p_ZL17INTTTwiddleFactor_7_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln106_1_fu_307_p2 = (l_fu_128 + 3'd1);

assign add_ln106_2_fu_295_p2 = (indvar_flatten32_fu_132 + 20'd1);

assign add_ln106_fu_377_p2 = (zext_ln106_fu_373_p1 + mem_in2);

assign add_ln108_1_fu_398_p2 = (indvar_flatten19_fu_124 + 19'd1);

assign add_ln108_fu_442_p2 = (select_ln106_fu_435_p3 + 6'd1);

assign add_ln109_fu_392_p2 = (t_1_mid2_fu_351_p3 + 13'd1);

assign add_ln110_fu_491_p2 = (tmp_s_fu_479_p4 + zext_ln110_fu_488_p1);

assign and_ln106_fu_331_p2 = (xor_ln106_fu_319_p2 & icmp_ln109_fu_325_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_block_state11_pp0_stage0_iter10)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_io)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_block_state11_pp0_stage0_iter10)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_io)));
end

always @ (*) begin
    ap_block_state11_pp0_stage0_iter10 = (m_axi_gmem1_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state3_io = ((m_axi_gmem1_ARREADY == 1'b0) & (first_iter_2_reg_577 == 1'd1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign empty_2312_fu_345_p2 = (icmp_ln108_fu_313_p2 | and_ln106_fu_331_p2);

assign first_iter_2_fu_359_p2 = ((t_1_mid2_fu_351_p3 == 13'd0) ? 1'b1 : 1'b0);

assign icmp_ln106_fu_289_p2 = ((indvar_flatten32_fu_132 == 20'd655360) ? 1'b1 : 1'b0);

assign icmp_ln108_fu_313_p2 = ((indvar_flatten19_fu_124 == 19'd131072) ? 1'b1 : 1'b0);

assign icmp_ln109_fu_325_p2 = ((t_fu_116 == 13'd4096) ? 1'b1 : 1'b0);

assign lshr_ln2_fu_469_p4 = {{select_ln108_fu_448_p3[4:3]}};

assign m_axi_gmem1_ARADDR = p_cast2_cast_fu_455_p1;

assign m_axi_gmem1_ARBURST = 2'd0;

assign m_axi_gmem1_ARCACHE = 4'd0;

assign m_axi_gmem1_ARID = 1'd0;

assign m_axi_gmem1_ARLEN = 64'd4096;

assign m_axi_gmem1_ARLOCK = 2'd0;

assign m_axi_gmem1_ARPROT = 3'd0;

assign m_axi_gmem1_ARQOS = 4'd0;

assign m_axi_gmem1_ARREGION = 4'd0;

assign m_axi_gmem1_ARSIZE = 3'd0;

assign m_axi_gmem1_ARUSER = 1'd0;

assign m_axi_gmem1_AWADDR = 64'd0;

assign m_axi_gmem1_AWBURST = 2'd0;

assign m_axi_gmem1_AWCACHE = 4'd0;

assign m_axi_gmem1_AWID = 1'd0;

assign m_axi_gmem1_AWLEN = 32'd0;

assign m_axi_gmem1_AWLOCK = 2'd0;

assign m_axi_gmem1_AWPROT = 3'd0;

assign m_axi_gmem1_AWQOS = 4'd0;

assign m_axi_gmem1_AWREGION = 4'd0;

assign m_axi_gmem1_AWSIZE = 3'd0;

assign m_axi_gmem1_AWUSER = 1'd0;

assign m_axi_gmem1_AWVALID = 1'b0;

assign m_axi_gmem1_BREADY = 1'b0;

assign m_axi_gmem1_WDATA = 64'd0;

assign m_axi_gmem1_WID = 1'd0;

assign m_axi_gmem1_WLAST = 1'b0;

assign m_axi_gmem1_WSTRB = 8'd0;

assign m_axi_gmem1_WUSER = 1'd0;

assign m_axi_gmem1_WVALID = 1'b0;

assign or_ln1_fu_365_p3 = {{select_ln106_1_fu_337_p3}, {15'd48}};

assign p_ZL17INTTTwiddleFactor_0_address0 = zext_ln110_1_fu_502_p1;

assign p_ZL17INTTTwiddleFactor_0_ce0 = p_ZL17INTTTwiddleFactor_0_ce0_local;

assign p_ZL17INTTTwiddleFactor_0_d0 = gmem1_addr_read_reg_601;

assign p_ZL17INTTTwiddleFactor_0_we0 = p_ZL17INTTTwiddleFactor_0_we0_local;

assign p_ZL17INTTTwiddleFactor_1_address0 = zext_ln110_1_fu_502_p1;

assign p_ZL17INTTTwiddleFactor_1_ce0 = p_ZL17INTTTwiddleFactor_1_ce0_local;

assign p_ZL17INTTTwiddleFactor_1_d0 = gmem1_addr_read_reg_601;

assign p_ZL17INTTTwiddleFactor_1_we0 = p_ZL17INTTTwiddleFactor_1_we0_local;

assign p_ZL17INTTTwiddleFactor_2_address0 = zext_ln110_1_fu_502_p1;

assign p_ZL17INTTTwiddleFactor_2_ce0 = p_ZL17INTTTwiddleFactor_2_ce0_local;

assign p_ZL17INTTTwiddleFactor_2_d0 = gmem1_addr_read_reg_601;

assign p_ZL17INTTTwiddleFactor_2_we0 = p_ZL17INTTTwiddleFactor_2_we0_local;

assign p_ZL17INTTTwiddleFactor_3_address0 = zext_ln110_1_fu_502_p1;

assign p_ZL17INTTTwiddleFactor_3_ce0 = p_ZL17INTTTwiddleFactor_3_ce0_local;

assign p_ZL17INTTTwiddleFactor_3_d0 = gmem1_addr_read_reg_601;

assign p_ZL17INTTTwiddleFactor_3_we0 = p_ZL17INTTTwiddleFactor_3_we0_local;

assign p_ZL17INTTTwiddleFactor_4_address0 = zext_ln110_1_fu_502_p1;

assign p_ZL17INTTTwiddleFactor_4_ce0 = p_ZL17INTTTwiddleFactor_4_ce0_local;

assign p_ZL17INTTTwiddleFactor_4_d0 = gmem1_addr_read_reg_601;

assign p_ZL17INTTTwiddleFactor_4_we0 = p_ZL17INTTTwiddleFactor_4_we0_local;

assign p_ZL17INTTTwiddleFactor_5_address0 = zext_ln110_1_fu_502_p1;

assign p_ZL17INTTTwiddleFactor_5_ce0 = p_ZL17INTTTwiddleFactor_5_ce0_local;

assign p_ZL17INTTTwiddleFactor_5_d0 = gmem1_addr_read_reg_601;

assign p_ZL17INTTTwiddleFactor_5_we0 = p_ZL17INTTTwiddleFactor_5_we0_local;

assign p_ZL17INTTTwiddleFactor_6_address0 = zext_ln110_1_fu_502_p1;

assign p_ZL17INTTTwiddleFactor_6_ce0 = p_ZL17INTTTwiddleFactor_6_ce0_local;

assign p_ZL17INTTTwiddleFactor_6_d0 = gmem1_addr_read_reg_601;

assign p_ZL17INTTTwiddleFactor_6_we0 = p_ZL17INTTTwiddleFactor_6_we0_local;

assign p_ZL17INTTTwiddleFactor_7_address0 = zext_ln110_1_fu_502_p1;

assign p_ZL17INTTTwiddleFactor_7_ce0 = p_ZL17INTTTwiddleFactor_7_ce0_local;

assign p_ZL17INTTTwiddleFactor_7_d0 = gmem1_addr_read_reg_601;

assign p_ZL17INTTTwiddleFactor_7_we0 = p_ZL17INTTTwiddleFactor_7_we0_local;

assign p_cast2_cast_fu_455_p1 = $signed(p_cast2_reg_581);

assign select_ln106_1_fu_337_p3 = ((icmp_ln108_fu_313_p2[0:0] == 1'b1) ? add_ln106_1_fu_307_p2 : l_fu_128);

assign select_ln106_fu_435_p3 = ((icmp_ln108_reg_557[0:0] == 1'b1) ? 6'd0 : b_fu_120);

assign select_ln108_1_fu_404_p3 = ((icmp_ln108_fu_313_p2[0:0] == 1'b1) ? 19'd1 : add_ln108_1_fu_398_p2);

assign select_ln108_fu_448_p3 = ((and_ln106_reg_562[0:0] == 1'b1) ? add_ln108_fu_442_p2 : select_ln106_fu_435_p3);

assign t_1_mid2_fu_351_p3 = ((empty_2312_fu_345_p2[0:0] == 1'b1) ? 13'd0 : t_fu_116);

assign tmp_s_fu_479_p4 = {{{select_ln106_1_reg_567}, {lshr_ln2_fu_469_p4}}, {12'd0}};

assign trunc_ln108_fu_465_p1 = select_ln108_fu_448_p3[2:0];

assign xor_ln106_fu_319_p2 = (icmp_ln108_fu_313_p2 ^ 1'd1);

assign zext_ln106_fu_373_p1 = or_ln1_fu_365_p3;

assign zext_ln110_1_fu_502_p1 = add_ln110_reg_596_pp0_iter10_reg;

assign zext_ln110_fu_488_p1 = t_1_mid2_reg_572;

endmodule //Top_Top_Pipeline_init_INTTTwiddle_Loop_VITIS_LOOP_108_3_VITIS_LOOP_109_4
