// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="Compute_BConv_Naive_Compute_BConv_Naive,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcu55c-fsvh2892-2L-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.612000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=120,HLS_SYN_DSP=0,HLS_SYN_FF=57233,HLS_SYN_LUT=42285,HLS_VERSION=2024_1}" *)

module Compute_BConv_Naive (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_x_address0,
        in_x_ce0,
        in_x_we0,
        in_x_d0,
        in_x_q0,
        in_w_address0,
        in_w_ce0,
        in_w_q0,
        out_mod_address0,
        out_mod_ce0,
        out_mod_q0,
        out_k_half_address0,
        out_k_half_ce0,
        out_k_half_we0,
        out_k_half_d0,
        out_k_half_q0,
        out_k_half_address1,
        out_k_half_ce1,
        out_k_half_we1,
        out_k_half_d1,
        out_k_half_q1,
        out_m_barrett_address0,
        out_m_barrett_ce0,
        out_m_barrett_we0,
        out_m_barrett_d0,
        out_m_barrett_q0,
        out_m_barrett_address1,
        out_m_barrett_ce1,
        out_m_barrett_we1,
        out_m_barrett_d1,
        out_m_barrett_q1,
        sizeP
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [14:0] in_x_address0;
output   in_x_ce0;
output   in_x_we0;
output  [63:0] in_x_d0;
input  [63:0] in_x_q0;
output  [3:0] in_w_address0;
output   in_w_ce0;
input  [63:0] in_w_q0;
output  [2:0] out_mod_address0;
output   out_mod_ce0;
input  [63:0] out_mod_q0;
output  [2:0] out_k_half_address0;
output   out_k_half_ce0;
output   out_k_half_we0;
output  [63:0] out_k_half_d0;
input  [63:0] out_k_half_q0;
output  [2:0] out_k_half_address1;
output   out_k_half_ce1;
output   out_k_half_we1;
output  [63:0] out_k_half_d1;
input  [63:0] out_k_half_q1;
output  [2:0] out_m_barrett_address0;
output   out_m_barrett_ce0;
output   out_m_barrett_we0;
output  [63:0] out_m_barrett_d0;
input  [63:0] out_m_barrett_q0;
output  [2:0] out_m_barrett_address1;
output   out_m_barrett_ce1;
output   out_m_barrett_we1;
output  [63:0] out_m_barrett_d1;
input  [63:0] out_m_barrett_q1;
input  [31:0] sizeP;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[14:0] in_x_address0;
reg in_x_ce0;
reg in_x_we0;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    ap_CS_fsm_state3;
wire   [43:0] tmp_5_fu_345_p3;
reg   [43:0] tmp_5_reg_539;
reg    local_in_x_ce0;
wire   [63:0] local_in_x_q0;
reg    local_in_x_ce1;
reg    local_in_x_we1;
reg    local_in_x_1_ce0;
wire   [63:0] local_in_x_1_q0;
reg    local_in_x_1_ce1;
reg    local_in_x_1_we1;
reg    local_in_x_2_ce0;
wire   [63:0] local_in_x_2_q0;
reg    local_in_x_2_ce1;
reg    local_in_x_2_we1;
reg    local_out_x_ce0;
wire   [63:0] local_out_x_q0;
reg    local_out_x_ce1;
reg    local_out_x_we1;
reg    local_out_x_1_ce0;
wire   [63:0] local_out_x_1_q0;
reg    local_out_x_1_ce1;
reg    local_out_x_1_we1;
reg    local_out_x_2_ce0;
wire   [63:0] local_out_x_2_q0;
reg    local_out_x_2_ce1;
reg    local_out_x_2_we1;
reg    local_out_x_3_ce0;
wire   [63:0] local_out_x_3_q0;
reg    local_out_x_3_ce1;
reg    local_out_x_3_we1;
reg    local_out_x_4_ce0;
wire   [63:0] local_out_x_4_q0;
reg    local_out_x_4_ce1;
reg    local_out_x_4_we1;
wire    grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_ap_start;
wire    grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_ap_done;
wire    grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_ap_idle;
wire    grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_ap_ready;
wire   [3:0] grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_in_w_address0;
wire    grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_in_w_ce0;
wire   [63:0] grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_14_out;
wire    grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_14_out_ap_vld;
wire   [63:0] grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_13_out;
wire    grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_13_out_ap_vld;
wire   [63:0] grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_12_out;
wire    grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_12_out_ap_vld;
wire   [63:0] grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_11_out;
wire    grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_11_out_ap_vld;
wire   [63:0] grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_10_out;
wire    grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_10_out_ap_vld;
wire   [63:0] grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_9_out;
wire    grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_9_out_ap_vld;
wire   [63:0] grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_8_out;
wire    grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_8_out_ap_vld;
wire   [63:0] grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_7_out;
wire    grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_7_out_ap_vld;
wire   [63:0] grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_6_out;
wire    grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_6_out_ap_vld;
wire   [63:0] grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_5_out;
wire    grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_5_out_ap_vld;
wire   [63:0] grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_4_out;
wire    grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_4_out_ap_vld;
wire   [63:0] grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_3_out;
wire    grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_3_out_ap_vld;
wire   [63:0] grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_2_out;
wire    grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_2_out_ap_vld;
wire   [63:0] grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_1_out;
wire    grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_1_out_ap_vld;
wire   [63:0] grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_out;
wire    grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_out_ap_vld;
wire    grp_Compute_BConv_Naive_Pipeline_Load_Mod_fu_195_ap_start;
wire    grp_Compute_BConv_Naive_Pipeline_Load_Mod_fu_195_ap_done;
wire    grp_Compute_BConv_Naive_Pipeline_Load_Mod_fu_195_ap_idle;
wire    grp_Compute_BConv_Naive_Pipeline_Load_Mod_fu_195_ap_ready;
wire   [2:0] grp_Compute_BConv_Naive_Pipeline_Load_Mod_fu_195_out_mod_address0;
wire    grp_Compute_BConv_Naive_Pipeline_Load_Mod_fu_195_out_mod_ce0;
wire   [63:0] grp_Compute_BConv_Naive_Pipeline_Load_Mod_fu_195_local_mod_4_out;
wire    grp_Compute_BConv_Naive_Pipeline_Load_Mod_fu_195_local_mod_4_out_ap_vld;
wire   [63:0] grp_Compute_BConv_Naive_Pipeline_Load_Mod_fu_195_local_mod_3_out;
wire    grp_Compute_BConv_Naive_Pipeline_Load_Mod_fu_195_local_mod_3_out_ap_vld;
wire   [63:0] grp_Compute_BConv_Naive_Pipeline_Load_Mod_fu_195_local_mod_2_out;
wire    grp_Compute_BConv_Naive_Pipeline_Load_Mod_fu_195_local_mod_2_out_ap_vld;
wire   [63:0] grp_Compute_BConv_Naive_Pipeline_Load_Mod_fu_195_local_mod_1_out;
wire    grp_Compute_BConv_Naive_Pipeline_Load_Mod_fu_195_local_mod_1_out_ap_vld;
wire   [63:0] grp_Compute_BConv_Naive_Pipeline_Load_Mod_fu_195_local_mod_out;
wire    grp_Compute_BConv_Naive_Pipeline_Load_Mod_fu_195_local_mod_out_ap_vld;
wire    grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_ap_start;
wire    grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_ap_done;
wire    grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_ap_idle;
wire    grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_ap_ready;
wire   [14:0] grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_in_x_address0;
wire    grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_in_x_ce0;
wire   [11:0] grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_local_in_x_2_address1;
wire    grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_local_in_x_2_ce1;
wire    grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_local_in_x_2_we1;
wire   [63:0] grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_local_in_x_2_d1;
wire   [11:0] grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_local_in_x_1_address1;
wire    grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_local_in_x_1_ce1;
wire    grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_local_in_x_1_we1;
wire   [63:0] grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_local_in_x_1_d1;
wire   [11:0] grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_local_in_x_address1;
wire    grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_local_in_x_ce1;
wire    grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_local_in_x_we1;
wire   [63:0] grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_local_in_x_d1;
wire    grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_ap_start;
wire    grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_ap_done;
wire    grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_ap_idle;
wire    grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_ap_ready;
wire   [11:0] grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_in_x_address0;
wire    grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_in_x_ce0;
wire   [11:0] grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_in_x_1_address0;
wire    grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_in_x_1_ce0;
wire   [11:0] grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_in_x_2_address0;
wire    grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_in_x_2_ce0;
wire   [11:0] grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_address1;
wire    grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_ce1;
wire    grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_we1;
wire   [63:0] grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_d1;
wire   [11:0] grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_1_address1;
wire    grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_1_ce1;
wire    grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_1_we1;
wire   [63:0] grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_1_d1;
wire   [11:0] grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_2_address1;
wire    grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_2_ce1;
wire    grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_2_we1;
wire   [63:0] grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_2_d1;
wire   [11:0] grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_3_address1;
wire    grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_3_ce1;
wire    grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_3_we1;
wire   [63:0] grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_3_d1;
wire   [11:0] grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_4_address1;
wire    grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_4_ce1;
wire    grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_4_we1;
wire   [63:0] grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_4_d1;
wire    grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_ap_start;
wire    grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_ap_done;
wire    grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_ap_idle;
wire    grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_ap_ready;
wire   [14:0] grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_in_x_address0;
wire    grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_in_x_ce0;
wire    grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_in_x_we0;
wire   [63:0] grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_in_x_d0;
wire   [11:0] grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_local_out_x_address0;
wire    grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_local_out_x_ce0;
wire   [11:0] grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_local_out_x_1_address0;
wire    grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_local_out_x_1_ce0;
wire   [11:0] grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_local_out_x_2_address0;
wire    grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_local_out_x_2_ce0;
wire   [11:0] grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_local_out_x_3_address0;
wire    grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_local_out_x_3_ce0;
wire   [11:0] grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_local_out_x_4_address0;
wire    grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_local_out_x_4_ce0;
reg    grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_Compute_BConv_Naive_Pipeline_Load_Mod_fu_195_ap_start_reg;
reg    grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_ap_start_reg;
reg    grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_ap_start_reg;
wire    ap_CS_fsm_state4;
reg    grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_ap_start_reg;
reg   [5:0] ap_NS_fsm;
wire    ap_NS_fsm_state5;
wire    ap_CS_fsm_state6;
reg    ap_ST_fsm_state1_blk;
reg    ap_block_state2_on_subcall_done;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_ap_start_reg = 1'b0;
#0 grp_Compute_BConv_Naive_Pipeline_Load_Mod_fu_195_ap_start_reg = 1'b0;
#0 grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_ap_start_reg = 1'b0;
#0 grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_ap_start_reg = 1'b0;
#0 grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_ap_start_reg = 1'b0;
end

Compute_BConv_Naive_local_in_x_RAM_2P_BRAM_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
local_in_x_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_in_x_address0),
    .ce0(local_in_x_ce0),
    .q0(local_in_x_q0),
    .address1(grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_local_in_x_address1),
    .ce1(local_in_x_ce1),
    .we1(local_in_x_we1),
    .d1(grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_local_in_x_d1)
);

Compute_BConv_Naive_local_in_x_RAM_2P_BRAM_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
local_in_x_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_in_x_1_address0),
    .ce0(local_in_x_1_ce0),
    .q0(local_in_x_1_q0),
    .address1(grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_local_in_x_1_address1),
    .ce1(local_in_x_1_ce1),
    .we1(local_in_x_1_we1),
    .d1(grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_local_in_x_1_d1)
);

Compute_BConv_Naive_local_in_x_RAM_2P_BRAM_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
local_in_x_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_in_x_2_address0),
    .ce0(local_in_x_2_ce0),
    .q0(local_in_x_2_q0),
    .address1(grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_local_in_x_2_address1),
    .ce1(local_in_x_2_ce1),
    .we1(local_in_x_2_we1),
    .d1(grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_local_in_x_2_d1)
);

Compute_BConv_Naive_local_in_x_RAM_2P_BRAM_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
local_out_x_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_local_out_x_address0),
    .ce0(local_out_x_ce0),
    .q0(local_out_x_q0),
    .address1(grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_address1),
    .ce1(local_out_x_ce1),
    .we1(local_out_x_we1),
    .d1(grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_d1)
);

Compute_BConv_Naive_local_in_x_RAM_2P_BRAM_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
local_out_x_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_local_out_x_1_address0),
    .ce0(local_out_x_1_ce0),
    .q0(local_out_x_1_q0),
    .address1(grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_1_address1),
    .ce1(local_out_x_1_ce1),
    .we1(local_out_x_1_we1),
    .d1(grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_1_d1)
);

Compute_BConv_Naive_local_in_x_RAM_2P_BRAM_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
local_out_x_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_local_out_x_2_address0),
    .ce0(local_out_x_2_ce0),
    .q0(local_out_x_2_q0),
    .address1(grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_2_address1),
    .ce1(local_out_x_2_ce1),
    .we1(local_out_x_2_we1),
    .d1(grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_2_d1)
);

Compute_BConv_Naive_local_in_x_RAM_2P_BRAM_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
local_out_x_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_local_out_x_3_address0),
    .ce0(local_out_x_3_ce0),
    .q0(local_out_x_3_q0),
    .address1(grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_3_address1),
    .ce1(local_out_x_3_ce1),
    .we1(local_out_x_3_we1),
    .d1(grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_3_d1)
);

Compute_BConv_Naive_local_in_x_RAM_2P_BRAM_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
local_out_x_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_local_out_x_4_address0),
    .ce0(local_out_x_4_ce0),
    .q0(local_out_x_4_q0),
    .address1(grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_4_address1),
    .ce1(local_out_x_4_ce1),
    .we1(local_out_x_4_we1),
    .d1(grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_4_d1)
);

Compute_BConv_Naive_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1 grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_ap_start),
    .ap_done(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_ap_done),
    .ap_idle(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_ap_idle),
    .ap_ready(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_ap_ready),
    .in_w_address0(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_in_w_address0),
    .in_w_ce0(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_in_w_ce0),
    .in_w_q0(in_w_q0),
    .local_w_14_out(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_14_out),
    .local_w_14_out_ap_vld(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_14_out_ap_vld),
    .local_w_13_out(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_13_out),
    .local_w_13_out_ap_vld(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_13_out_ap_vld),
    .local_w_12_out(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_12_out),
    .local_w_12_out_ap_vld(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_12_out_ap_vld),
    .local_w_11_out(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_11_out),
    .local_w_11_out_ap_vld(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_11_out_ap_vld),
    .local_w_10_out(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_10_out),
    .local_w_10_out_ap_vld(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_10_out_ap_vld),
    .local_w_9_out(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_9_out),
    .local_w_9_out_ap_vld(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_9_out_ap_vld),
    .local_w_8_out(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_8_out),
    .local_w_8_out_ap_vld(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_8_out_ap_vld),
    .local_w_7_out(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_7_out),
    .local_w_7_out_ap_vld(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_7_out_ap_vld),
    .local_w_6_out(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_6_out),
    .local_w_6_out_ap_vld(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_6_out_ap_vld),
    .local_w_5_out(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_5_out),
    .local_w_5_out_ap_vld(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_5_out_ap_vld),
    .local_w_4_out(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_4_out),
    .local_w_4_out_ap_vld(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_4_out_ap_vld),
    .local_w_3_out(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_3_out),
    .local_w_3_out_ap_vld(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_3_out_ap_vld),
    .local_w_2_out(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_2_out),
    .local_w_2_out_ap_vld(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_2_out_ap_vld),
    .local_w_1_out(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_1_out),
    .local_w_1_out_ap_vld(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_1_out_ap_vld),
    .local_w_out(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_out),
    .local_w_out_ap_vld(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_out_ap_vld)
);

Compute_BConv_Naive_Compute_BConv_Naive_Pipeline_Load_Mod grp_Compute_BConv_Naive_Pipeline_Load_Mod_fu_195(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Compute_BConv_Naive_Pipeline_Load_Mod_fu_195_ap_start),
    .ap_done(grp_Compute_BConv_Naive_Pipeline_Load_Mod_fu_195_ap_done),
    .ap_idle(grp_Compute_BConv_Naive_Pipeline_Load_Mod_fu_195_ap_idle),
    .ap_ready(grp_Compute_BConv_Naive_Pipeline_Load_Mod_fu_195_ap_ready),
    .out_mod_address0(grp_Compute_BConv_Naive_Pipeline_Load_Mod_fu_195_out_mod_address0),
    .out_mod_ce0(grp_Compute_BConv_Naive_Pipeline_Load_Mod_fu_195_out_mod_ce0),
    .out_mod_q0(out_mod_q0),
    .local_mod_4_out(grp_Compute_BConv_Naive_Pipeline_Load_Mod_fu_195_local_mod_4_out),
    .local_mod_4_out_ap_vld(grp_Compute_BConv_Naive_Pipeline_Load_Mod_fu_195_local_mod_4_out_ap_vld),
    .local_mod_3_out(grp_Compute_BConv_Naive_Pipeline_Load_Mod_fu_195_local_mod_3_out),
    .local_mod_3_out_ap_vld(grp_Compute_BConv_Naive_Pipeline_Load_Mod_fu_195_local_mod_3_out_ap_vld),
    .local_mod_2_out(grp_Compute_BConv_Naive_Pipeline_Load_Mod_fu_195_local_mod_2_out),
    .local_mod_2_out_ap_vld(grp_Compute_BConv_Naive_Pipeline_Load_Mod_fu_195_local_mod_2_out_ap_vld),
    .local_mod_1_out(grp_Compute_BConv_Naive_Pipeline_Load_Mod_fu_195_local_mod_1_out),
    .local_mod_1_out_ap_vld(grp_Compute_BConv_Naive_Pipeline_Load_Mod_fu_195_local_mod_1_out_ap_vld),
    .local_mod_out(grp_Compute_BConv_Naive_Pipeline_Load_Mod_fu_195_local_mod_out),
    .local_mod_out_ap_vld(grp_Compute_BConv_Naive_Pipeline_Load_Mod_fu_195_local_mod_out_ap_vld)
);

Compute_BConv_Naive_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3 grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_ap_start),
    .ap_done(grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_ap_done),
    .ap_idle(grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_ap_idle),
    .ap_ready(grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_ap_ready),
    .in_x_address0(grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_in_x_address0),
    .in_x_ce0(grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_in_x_ce0),
    .in_x_q0(in_x_q0),
    .local_in_x_2_address1(grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_local_in_x_2_address1),
    .local_in_x_2_ce1(grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_local_in_x_2_ce1),
    .local_in_x_2_we1(grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_local_in_x_2_we1),
    .local_in_x_2_d1(grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_local_in_x_2_d1),
    .local_in_x_1_address1(grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_local_in_x_1_address1),
    .local_in_x_1_ce1(grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_local_in_x_1_ce1),
    .local_in_x_1_we1(grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_local_in_x_1_we1),
    .local_in_x_1_d1(grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_local_in_x_1_d1),
    .local_in_x_address1(grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_local_in_x_address1),
    .local_in_x_ce1(grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_local_in_x_ce1),
    .local_in_x_we1(grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_local_in_x_we1),
    .local_in_x_d1(grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_local_in_x_d1)
);

Compute_BConv_Naive_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4 grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_ap_start),
    .ap_done(grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_ap_done),
    .ap_idle(grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_ap_idle),
    .ap_ready(grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_ap_ready),
    .sizeP(sizeP),
    .zext_ln66_1(tmp_5_reg_539),
    .local_in_x_address0(grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_in_x_address0),
    .local_in_x_ce0(grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_in_x_ce0),
    .local_in_x_q0(local_in_x_q0),
    .local_in_x_1_address0(grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_in_x_1_address0),
    .local_in_x_1_ce0(grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_in_x_1_ce0),
    .local_in_x_1_q0(local_in_x_1_q0),
    .local_in_x_2_address0(grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_in_x_2_address0),
    .local_in_x_2_ce0(grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_in_x_2_ce0),
    .local_in_x_2_q0(local_in_x_2_q0),
    .local_out_x_address1(grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_address1),
    .local_out_x_ce1(grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_ce1),
    .local_out_x_we1(grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_we1),
    .local_out_x_d1(grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_d1),
    .local_out_x_1_address1(grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_1_address1),
    .local_out_x_1_ce1(grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_1_ce1),
    .local_out_x_1_we1(grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_1_we1),
    .local_out_x_1_d1(grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_1_d1),
    .local_out_x_2_address1(grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_2_address1),
    .local_out_x_2_ce1(grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_2_ce1),
    .local_out_x_2_we1(grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_2_we1),
    .local_out_x_2_d1(grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_2_d1),
    .local_out_x_3_address1(grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_3_address1),
    .local_out_x_3_ce1(grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_3_ce1),
    .local_out_x_3_we1(grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_3_we1),
    .local_out_x_3_d1(grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_3_d1),
    .local_out_x_4_address1(grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_4_address1),
    .local_out_x_4_ce1(grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_4_ce1),
    .local_out_x_4_we1(grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_4_we1),
    .local_out_x_4_d1(grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_4_d1),
    .local_mod_reload(grp_Compute_BConv_Naive_Pipeline_Load_Mod_fu_195_local_mod_out),
    .local_mod_1_reload(grp_Compute_BConv_Naive_Pipeline_Load_Mod_fu_195_local_mod_1_out),
    .local_mod_2_reload(grp_Compute_BConv_Naive_Pipeline_Load_Mod_fu_195_local_mod_2_out),
    .local_mod_3_reload(grp_Compute_BConv_Naive_Pipeline_Load_Mod_fu_195_local_mod_3_out),
    .local_mod_4_reload(grp_Compute_BConv_Naive_Pipeline_Load_Mod_fu_195_local_mod_4_out),
    .local_w_reload(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_out),
    .local_w_1_reload(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_1_out),
    .local_w_2_reload(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_2_out),
    .local_w_3_reload(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_3_out),
    .local_w_4_reload(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_4_out),
    .local_w_5_reload(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_5_out),
    .local_w_6_reload(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_6_out),
    .local_w_7_reload(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_7_out),
    .local_w_8_reload(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_8_out),
    .local_w_9_reload(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_9_out),
    .local_w_10_reload(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_10_out),
    .local_w_11_reload(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_11_out),
    .local_w_12_reload(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_12_out),
    .local_w_13_reload(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_13_out),
    .local_w_14_reload(grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_local_w_14_out)
);

Compute_BConv_Naive_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7 grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_ap_start),
    .ap_done(grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_ap_done),
    .ap_idle(grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_ap_idle),
    .ap_ready(grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_ap_ready),
    .zext_ln66_1(tmp_5_reg_539),
    .in_x_address0(grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_in_x_address0),
    .in_x_ce0(grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_in_x_ce0),
    .in_x_we0(grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_in_x_we0),
    .in_x_d0(grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_in_x_d0),
    .local_out_x_address0(grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_local_out_x_address0),
    .local_out_x_ce0(grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_local_out_x_ce0),
    .local_out_x_q0(local_out_x_q0),
    .local_out_x_1_address0(grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_local_out_x_1_address0),
    .local_out_x_1_ce0(grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_local_out_x_1_ce0),
    .local_out_x_1_q0(local_out_x_1_q0),
    .local_out_x_2_address0(grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_local_out_x_2_address0),
    .local_out_x_2_ce0(grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_local_out_x_2_ce0),
    .local_out_x_2_q0(local_out_x_2_q0),
    .local_out_x_3_address0(grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_local_out_x_3_address0),
    .local_out_x_3_ce0(grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_local_out_x_3_ce0),
    .local_out_x_3_q0(local_out_x_3_q0),
    .local_out_x_4_address0(grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_local_out_x_4_address0),
    .local_out_x_4_ce0(grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_local_out_x_4_ce0),
    .local_out_x_4_q0(local_out_x_4_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_ap_start_reg <= 1'b1;
        end else if ((grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_ap_ready == 1'b1)) begin
            grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Compute_BConv_Naive_Pipeline_Load_Mod_fu_195_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_Compute_BConv_Naive_Pipeline_Load_Mod_fu_195_ap_start_reg <= 1'b1;
        end else if ((grp_Compute_BConv_Naive_Pipeline_Load_Mod_fu_195_ap_ready == 1'b1)) begin
            grp_Compute_BConv_Naive_Pipeline_Load_Mod_fu_195_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_ap_start_reg <= 1'b1;
        end else if ((grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_ap_ready == 1'b1)) begin
            grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_ap_start_reg <= 1'b1;
        end else if ((grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_ap_ready == 1'b1)) begin
            grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state5) & (1'b1 == ap_CS_fsm_state4))) begin
            grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_ap_start_reg <= 1'b1;
        end else if ((grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_ap_ready == 1'b1)) begin
            grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        tmp_5_reg_539[43 : 12] <= tmp_5_fu_345_p3[43 : 12];
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_on_subcall_done)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        in_x_address0 = grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_in_x_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        in_x_address0 = grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_in_x_address0;
    end else begin
        in_x_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        in_x_ce0 = grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_in_x_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        in_x_ce0 = grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_in_x_ce0;
    end else begin
        in_x_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        in_x_we0 = grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_in_x_we0;
    end else begin
        in_x_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        local_in_x_1_ce0 = grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_in_x_1_ce0;
    end else begin
        local_in_x_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        local_in_x_1_ce1 = grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_local_in_x_1_ce1;
    end else begin
        local_in_x_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        local_in_x_1_we1 = grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_local_in_x_1_we1;
    end else begin
        local_in_x_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        local_in_x_2_ce0 = grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_in_x_2_ce0;
    end else begin
        local_in_x_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        local_in_x_2_ce1 = grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_local_in_x_2_ce1;
    end else begin
        local_in_x_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        local_in_x_2_we1 = grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_local_in_x_2_we1;
    end else begin
        local_in_x_2_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        local_in_x_ce0 = grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_in_x_ce0;
    end else begin
        local_in_x_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        local_in_x_ce1 = grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_local_in_x_ce1;
    end else begin
        local_in_x_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        local_in_x_we1 = grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_local_in_x_we1;
    end else begin
        local_in_x_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        local_out_x_1_ce0 = grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_local_out_x_1_ce0;
    end else begin
        local_out_x_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        local_out_x_1_ce1 = grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_1_ce1;
    end else begin
        local_out_x_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        local_out_x_1_we1 = grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_1_we1;
    end else begin
        local_out_x_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        local_out_x_2_ce0 = grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_local_out_x_2_ce0;
    end else begin
        local_out_x_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        local_out_x_2_ce1 = grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_2_ce1;
    end else begin
        local_out_x_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        local_out_x_2_we1 = grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_2_we1;
    end else begin
        local_out_x_2_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        local_out_x_3_ce0 = grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_local_out_x_3_ce0;
    end else begin
        local_out_x_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        local_out_x_3_ce1 = grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_3_ce1;
    end else begin
        local_out_x_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        local_out_x_3_we1 = grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_3_we1;
    end else begin
        local_out_x_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        local_out_x_4_ce0 = grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_local_out_x_4_ce0;
    end else begin
        local_out_x_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        local_out_x_4_ce1 = grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_4_ce1;
    end else begin
        local_out_x_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        local_out_x_4_we1 = grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_4_we1;
    end else begin
        local_out_x_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        local_out_x_ce0 = grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_local_out_x_ce0;
    end else begin
        local_out_x_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        local_out_x_ce1 = grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_ce1;
    end else begin
        local_out_x_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        local_out_x_we1 = grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_local_out_x_we1;
    end else begin
        local_out_x_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_NS_fsm_state5 = ap_NS_fsm[32'd4];

always @ (*) begin
    ap_block_state2_on_subcall_done = ((grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_ap_done == 1'b0) | (grp_Compute_BConv_Naive_Pipeline_Load_Mod_fu_195_ap_done == 1'b0) | (grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_ap_done == 1'b0));
end

assign grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_ap_start = grp_Compute_BConv_Naive_Pipeline_Compute_Loop_VITIS_LOOP_67_4_fu_218_ap_start_reg;

assign grp_Compute_BConv_Naive_Pipeline_Load_Mod_fu_195_ap_start = grp_Compute_BConv_Naive_Pipeline_Load_Mod_fu_195_ap_start_reg;

assign grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_ap_start = grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_ap_start_reg;

assign grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_ap_start = grp_Compute_BConv_Naive_Pipeline_Load_X_VITIS_LOOP_55_2_VITIS_LOOP_56_3_fu_206_ap_start_reg;

assign grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_ap_start = grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_ap_start_reg;

assign in_w_address0 = grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_in_w_address0;

assign in_w_ce0 = grp_Compute_BConv_Naive_Pipeline_Load_W_VITIS_LOOP_40_1_fu_174_in_w_ce0;

assign in_x_d0 = grp_Compute_BConv_Naive_Pipeline_Store_X_VITIS_LOOP_88_6_VITIS_LOOP_89_7_fu_253_in_x_d0;

assign out_k_half_address0 = 3'd0;

assign out_k_half_address1 = 3'd0;

assign out_k_half_ce0 = 1'b0;

assign out_k_half_ce1 = 1'b0;

assign out_k_half_d0 = 64'd0;

assign out_k_half_d1 = 64'd0;

assign out_k_half_we0 = 1'b0;

assign out_k_half_we1 = 1'b0;

assign out_m_barrett_address0 = 3'd0;

assign out_m_barrett_address1 = 3'd0;

assign out_m_barrett_ce0 = 1'b0;

assign out_m_barrett_ce1 = 1'b0;

assign out_m_barrett_d0 = 64'd0;

assign out_m_barrett_d1 = 64'd0;

assign out_m_barrett_we0 = 1'b0;

assign out_m_barrett_we1 = 1'b0;

assign out_mod_address0 = grp_Compute_BConv_Naive_Pipeline_Load_Mod_fu_195_out_mod_address0;

assign out_mod_ce0 = grp_Compute_BConv_Naive_Pipeline_Load_Mod_fu_195_out_mod_ce0;

assign tmp_5_fu_345_p3 = {{sizeP}, {12'd0}};

always @ (posedge ap_clk) begin
    tmp_5_reg_539[11:0] <= 12'b000000000000;
end

endmodule //Compute_BConv_Naive
