-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Top_Top_Pipeline_init_NTTTwiddle_Loop_VITIS_LOOP_99_1_VITIS_LOOP_100_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem0_AWREADY : IN STD_LOGIC;
    m_axi_gmem0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_WVALID : OUT STD_LOGIC;
    m_axi_gmem0_WREADY : IN STD_LOGIC;
    m_axi_gmem0_WDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_WSTRB : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem0_WLAST : OUT STD_LOGIC;
    m_axi_gmem0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem0_ARREADY : IN STD_LOGIC;
    m_axi_gmem0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RVALID : IN STD_LOGIC;
    m_axi_gmem0_RREADY : OUT STD_LOGIC;
    m_axi_gmem0_RDATA : IN STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_RLAST : IN STD_LOGIC;
    m_axi_gmem0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_BVALID : IN STD_LOGIC;
    m_axi_gmem0_BREADY : OUT STD_LOGIC;
    m_axi_gmem0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    mem_in1 : IN STD_LOGIC_VECTOR (63 downto 0);
    p_ZL16NTTTwiddleFactor_0_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    p_ZL16NTTTwiddleFactor_0_ce0 : OUT STD_LOGIC;
    p_ZL16NTTTwiddleFactor_0_we0 : OUT STD_LOGIC;
    p_ZL16NTTTwiddleFactor_0_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    p_ZL16NTTTwiddleFactor_1_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    p_ZL16NTTTwiddleFactor_1_ce0 : OUT STD_LOGIC;
    p_ZL16NTTTwiddleFactor_1_we0 : OUT STD_LOGIC;
    p_ZL16NTTTwiddleFactor_1_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    p_ZL16NTTTwiddleFactor_2_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    p_ZL16NTTTwiddleFactor_2_ce0 : OUT STD_LOGIC;
    p_ZL16NTTTwiddleFactor_2_we0 : OUT STD_LOGIC;
    p_ZL16NTTTwiddleFactor_2_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    p_ZL16NTTTwiddleFactor_3_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    p_ZL16NTTTwiddleFactor_3_ce0 : OUT STD_LOGIC;
    p_ZL16NTTTwiddleFactor_3_we0 : OUT STD_LOGIC;
    p_ZL16NTTTwiddleFactor_3_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    p_ZL16NTTTwiddleFactor_4_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    p_ZL16NTTTwiddleFactor_4_ce0 : OUT STD_LOGIC;
    p_ZL16NTTTwiddleFactor_4_we0 : OUT STD_LOGIC;
    p_ZL16NTTTwiddleFactor_4_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    p_ZL16NTTTwiddleFactor_5_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    p_ZL16NTTTwiddleFactor_5_ce0 : OUT STD_LOGIC;
    p_ZL16NTTTwiddleFactor_5_we0 : OUT STD_LOGIC;
    p_ZL16NTTTwiddleFactor_5_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    p_ZL16NTTTwiddleFactor_6_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    p_ZL16NTTTwiddleFactor_6_ce0 : OUT STD_LOGIC;
    p_ZL16NTTTwiddleFactor_6_we0 : OUT STD_LOGIC;
    p_ZL16NTTTwiddleFactor_6_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    p_ZL16NTTTwiddleFactor_7_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    p_ZL16NTTTwiddleFactor_7_ce0 : OUT STD_LOGIC;
    p_ZL16NTTTwiddleFactor_7_we0 : OUT STD_LOGIC;
    p_ZL16NTTTwiddleFactor_7_d0 : OUT STD_LOGIC_VECTOR (63 downto 0) );
end;


architecture behav of Top_Top_Pipeline_init_NTTTwiddle_Loop_VITIS_LOOP_99_1_VITIS_LOOP_100_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv64_1000 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000001000000000000";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv19_0 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000000";
    constant ap_const_lv20_0 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv20_A0000 : STD_LOGIC_VECTOR (19 downto 0) := "10100000000000000000";
    constant ap_const_lv20_1 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000001";
    constant ap_const_lv19_20000 : STD_LOGIC_VECTOR (18 downto 0) := "0100000000000000000";
    constant ap_const_lv13_1000 : STD_LOGIC_VECTOR (12 downto 0) := "1000000000000";
    constant ap_const_lv15_48 : STD_LOGIC_VECTOR (14 downto 0) := "000000001001000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv19_1 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000001";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal first_iter_0_reg_577 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_io : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter10 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln97_fu_289_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem0_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal gmem0_blk_n_AR : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln99_fu_313_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln99_reg_557 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln97_fu_331_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln97_reg_562 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln97_1_fu_337_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln97_1_reg_567 : STD_LOGIC_VECTOR (2 downto 0);
    signal t_mid2_fu_351_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal t_mid2_reg_572 : STD_LOGIC_VECTOR (12 downto 0);
    signal first_iter_0_fu_359_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_cast_reg_581 : STD_LOGIC_VECTOR (60 downto 0);
    signal trunc_ln99_fu_465_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln99_reg_592 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln99_reg_592_pp0_iter3_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln99_reg_592_pp0_iter4_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln99_reg_592_pp0_iter5_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln99_reg_592_pp0_iter6_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln99_reg_592_pp0_iter7_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln99_reg_592_pp0_iter8_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln99_reg_592_pp0_iter9_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln99_reg_592_pp0_iter10_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln101_fu_491_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln101_reg_596 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln101_reg_596_pp0_iter3_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln101_reg_596_pp0_iter4_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln101_reg_596_pp0_iter5_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln101_reg_596_pp0_iter6_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln101_reg_596_pp0_iter7_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln101_reg_596_pp0_iter8_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln101_reg_596_pp0_iter9_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln101_reg_596_pp0_iter10_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal gmem0_addr_read_reg_601 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln101_1_fu_502_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_cast_cast_fu_455_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal t_fu_116 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    signal add_ln100_fu_392_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal b_fu_120 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal select_ln99_fu_448_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal indvar_flatten_fu_124 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000000";
    signal select_ln99_1_fu_404_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal l_fu_128 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal indvar_flatten12_fu_132 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    signal add_ln97_2_fu_295_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal p_ZL16NTTTwiddleFactor_6_we0_local : STD_LOGIC;
    signal p_ZL16NTTTwiddleFactor_6_ce0_local : STD_LOGIC;
    signal p_ZL16NTTTwiddleFactor_5_we0_local : STD_LOGIC;
    signal p_ZL16NTTTwiddleFactor_5_ce0_local : STD_LOGIC;
    signal p_ZL16NTTTwiddleFactor_4_we0_local : STD_LOGIC;
    signal p_ZL16NTTTwiddleFactor_4_ce0_local : STD_LOGIC;
    signal p_ZL16NTTTwiddleFactor_3_we0_local : STD_LOGIC;
    signal p_ZL16NTTTwiddleFactor_3_ce0_local : STD_LOGIC;
    signal p_ZL16NTTTwiddleFactor_2_we0_local : STD_LOGIC;
    signal p_ZL16NTTTwiddleFactor_2_ce0_local : STD_LOGIC;
    signal p_ZL16NTTTwiddleFactor_1_we0_local : STD_LOGIC;
    signal p_ZL16NTTTwiddleFactor_1_ce0_local : STD_LOGIC;
    signal p_ZL16NTTTwiddleFactor_0_we0_local : STD_LOGIC;
    signal p_ZL16NTTTwiddleFactor_0_ce0_local : STD_LOGIC;
    signal p_ZL16NTTTwiddleFactor_7_we0_local : STD_LOGIC;
    signal p_ZL16NTTTwiddleFactor_7_ce0_local : STD_LOGIC;
    signal icmp_ln100_fu_325_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln97_fu_319_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln97_1_fu_307_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal empty_2310_fu_345_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln_fu_365_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln97_fu_373_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln97_fu_377_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln99_1_fu_398_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal select_ln97_fu_435_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln99_fu_442_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal lshr_ln1_fu_469_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_s_fu_479_p4 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln101_fu_488_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component Top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component Top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter10_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    b_fu_120_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    b_fu_120 <= ap_const_lv6_0;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    b_fu_120 <= select_ln99_fu_448_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten12_fu_132_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten12_fu_132 <= ap_const_lv20_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln97_fu_289_p2 = ap_const_lv1_0))) then 
                    indvar_flatten12_fu_132 <= add_ln97_2_fu_295_p2;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_124_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_124 <= ap_const_lv19_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln97_fu_289_p2 = ap_const_lv1_0))) then 
                    indvar_flatten_fu_124 <= select_ln99_1_fu_404_p3;
                end if;
            end if; 
        end if;
    end process;

    l_fu_128_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    l_fu_128 <= ap_const_lv3_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln97_fu_289_p2 = ap_const_lv1_0))) then 
                    l_fu_128 <= select_ln97_1_fu_337_p3;
                end if;
            end if; 
        end if;
    end process;

    t_fu_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    t_fu_116 <= ap_const_lv13_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln97_fu_289_p2 = ap_const_lv1_0))) then 
                    t_fu_116 <= add_ln100_fu_392_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln101_reg_596 <= add_ln101_fu_491_p2;
                add_ln101_reg_596_pp0_iter10_reg <= add_ln101_reg_596_pp0_iter9_reg;
                add_ln101_reg_596_pp0_iter3_reg <= add_ln101_reg_596;
                add_ln101_reg_596_pp0_iter4_reg <= add_ln101_reg_596_pp0_iter3_reg;
                add_ln101_reg_596_pp0_iter5_reg <= add_ln101_reg_596_pp0_iter4_reg;
                add_ln101_reg_596_pp0_iter6_reg <= add_ln101_reg_596_pp0_iter5_reg;
                add_ln101_reg_596_pp0_iter7_reg <= add_ln101_reg_596_pp0_iter6_reg;
                add_ln101_reg_596_pp0_iter8_reg <= add_ln101_reg_596_pp0_iter7_reg;
                add_ln101_reg_596_pp0_iter9_reg <= add_ln101_reg_596_pp0_iter8_reg;
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                gmem0_addr_read_reg_601 <= m_axi_gmem0_RDATA;
                trunc_ln99_reg_592 <= trunc_ln99_fu_465_p1;
                trunc_ln99_reg_592_pp0_iter10_reg <= trunc_ln99_reg_592_pp0_iter9_reg;
                trunc_ln99_reg_592_pp0_iter3_reg <= trunc_ln99_reg_592;
                trunc_ln99_reg_592_pp0_iter4_reg <= trunc_ln99_reg_592_pp0_iter3_reg;
                trunc_ln99_reg_592_pp0_iter5_reg <= trunc_ln99_reg_592_pp0_iter4_reg;
                trunc_ln99_reg_592_pp0_iter6_reg <= trunc_ln99_reg_592_pp0_iter5_reg;
                trunc_ln99_reg_592_pp0_iter7_reg <= trunc_ln99_reg_592_pp0_iter6_reg;
                trunc_ln99_reg_592_pp0_iter8_reg <= trunc_ln99_reg_592_pp0_iter7_reg;
                trunc_ln99_reg_592_pp0_iter9_reg <= trunc_ln99_reg_592_pp0_iter8_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                and_ln97_reg_562 <= and_ln97_fu_331_p2;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
                first_iter_0_reg_577 <= first_iter_0_fu_359_p2;
                icmp_ln99_reg_557 <= icmp_ln99_fu_313_p2;
                p_cast_reg_581 <= add_ln97_fu_377_p2(63 downto 3);
                select_ln97_1_reg_567 <= select_ln97_1_fu_337_p3;
                t_mid2_reg_572 <= t_mid2_fu_351_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln100_fu_392_p2 <= std_logic_vector(unsigned(t_mid2_fu_351_p3) + unsigned(ap_const_lv13_1));
    add_ln101_fu_491_p2 <= std_logic_vector(unsigned(tmp_s_fu_479_p4) + unsigned(zext_ln101_fu_488_p1));
    add_ln97_1_fu_307_p2 <= std_logic_vector(unsigned(l_fu_128) + unsigned(ap_const_lv3_1));
    add_ln97_2_fu_295_p2 <= std_logic_vector(unsigned(indvar_flatten12_fu_132) + unsigned(ap_const_lv20_1));
    add_ln97_fu_377_p2 <= std_logic_vector(unsigned(zext_ln97_fu_373_p1) + unsigned(mem_in1));
    add_ln99_1_fu_398_p2 <= std_logic_vector(unsigned(indvar_flatten_fu_124) + unsigned(ap_const_lv19_1));
    add_ln99_fu_442_p2 <= std_logic_vector(unsigned(select_ln97_fu_435_p3) + unsigned(ap_const_lv6_1));
    and_ln97_fu_331_p2 <= (xor_ln97_fu_319_p2 and icmp_ln100_fu_325_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter10, ap_block_state3_io, ap_block_state11_pp0_stage0_iter10)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state11_pp0_stage0_iter10)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_io)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter10, ap_block_state3_io, ap_block_state11_pp0_stage0_iter10)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state11_pp0_stage0_iter10)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_io)));
    end process;


    ap_block_state11_pp0_stage0_iter10_assign_proc : process(m_axi_gmem0_RVALID)
    begin
                ap_block_state11_pp0_stage0_iter10 <= (m_axi_gmem0_RVALID = ap_const_logic_0);
    end process;


    ap_block_state3_io_assign_proc : process(m_axi_gmem0_ARREADY, first_iter_0_reg_577)
    begin
                ap_block_state3_io <= ((m_axi_gmem0_ARREADY = ap_const_logic_0) and (first_iter_0_reg_577 = ap_const_lv1_1));
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln97_fu_289_p2)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln97_fu_289_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter10_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter10_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    empty_2310_fu_345_p2 <= (icmp_ln99_fu_313_p2 or and_ln97_fu_331_p2);
    first_iter_0_fu_359_p2 <= "1" when (t_mid2_fu_351_p3 = ap_const_lv13_0) else "0";

    gmem0_blk_n_AR_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_gmem0_ARREADY, first_iter_0_reg_577, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (first_iter_0_reg_577 = ap_const_lv1_1))) then 
            gmem0_blk_n_AR <= m_axi_gmem0_ARREADY;
        else 
            gmem0_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    gmem0_blk_n_R_assign_proc : process(ap_enable_reg_pp0_iter10, m_axi_gmem0_RVALID, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            gmem0_blk_n_R <= m_axi_gmem0_RVALID;
        else 
            gmem0_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln100_fu_325_p2 <= "1" when (t_fu_116 = ap_const_lv13_1000) else "0";
    icmp_ln97_fu_289_p2 <= "1" when (indvar_flatten12_fu_132 = ap_const_lv20_A0000) else "0";
    icmp_ln99_fu_313_p2 <= "1" when (indvar_flatten_fu_124 = ap_const_lv19_20000) else "0";
    lshr_ln1_fu_469_p4 <= select_ln99_fu_448_p3(4 downto 3);
    m_axi_gmem0_ARADDR <= p_cast_cast_fu_455_p1;
    m_axi_gmem0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem0_ARID <= ap_const_lv1_0;
    m_axi_gmem0_ARLEN <= ap_const_lv64_1000(32 - 1 downto 0);
    m_axi_gmem0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem0_ARUSER <= ap_const_lv1_0;

    m_axi_gmem0_ARVALID_assign_proc : process(ap_enable_reg_pp0_iter2, first_iter_0_reg_577, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (first_iter_0_reg_577 = ap_const_lv1_1))) then 
            m_axi_gmem0_ARVALID <= ap_const_logic_1;
        else 
            m_axi_gmem0_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem0_AWID <= ap_const_lv1_0;
    m_axi_gmem0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem0_AWVALID <= ap_const_logic_0;
    m_axi_gmem0_BREADY <= ap_const_logic_0;

    m_axi_gmem0_RREADY_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axi_gmem0_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem0_WDATA <= ap_const_lv64_0;
    m_axi_gmem0_WID <= ap_const_lv1_0;
    m_axi_gmem0_WLAST <= ap_const_logic_0;
    m_axi_gmem0_WSTRB <= ap_const_lv8_0;
    m_axi_gmem0_WUSER <= ap_const_lv1_0;
    m_axi_gmem0_WVALID <= ap_const_logic_0;
    or_ln_fu_365_p3 <= (select_ln97_1_fu_337_p3 & ap_const_lv15_48);
    p_ZL16NTTTwiddleFactor_0_address0 <= zext_ln101_1_fu_502_p1(17 - 1 downto 0);
    p_ZL16NTTTwiddleFactor_0_ce0 <= p_ZL16NTTTwiddleFactor_0_ce0_local;

    p_ZL16NTTTwiddleFactor_0_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            p_ZL16NTTTwiddleFactor_0_ce0_local <= ap_const_logic_1;
        else 
            p_ZL16NTTTwiddleFactor_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL16NTTTwiddleFactor_0_d0 <= gmem0_addr_read_reg_601;
    p_ZL16NTTTwiddleFactor_0_we0 <= p_ZL16NTTTwiddleFactor_0_we0_local;

    p_ZL16NTTTwiddleFactor_0_we0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001, trunc_ln99_reg_592_pp0_iter10_reg)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln99_reg_592_pp0_iter10_reg = ap_const_lv3_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            p_ZL16NTTTwiddleFactor_0_we0_local <= ap_const_logic_1;
        else 
            p_ZL16NTTTwiddleFactor_0_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL16NTTTwiddleFactor_1_address0 <= zext_ln101_1_fu_502_p1(17 - 1 downto 0);
    p_ZL16NTTTwiddleFactor_1_ce0 <= p_ZL16NTTTwiddleFactor_1_ce0_local;

    p_ZL16NTTTwiddleFactor_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            p_ZL16NTTTwiddleFactor_1_ce0_local <= ap_const_logic_1;
        else 
            p_ZL16NTTTwiddleFactor_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL16NTTTwiddleFactor_1_d0 <= gmem0_addr_read_reg_601;
    p_ZL16NTTTwiddleFactor_1_we0 <= p_ZL16NTTTwiddleFactor_1_we0_local;

    p_ZL16NTTTwiddleFactor_1_we0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001, trunc_ln99_reg_592_pp0_iter10_reg)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln99_reg_592_pp0_iter10_reg = ap_const_lv3_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            p_ZL16NTTTwiddleFactor_1_we0_local <= ap_const_logic_1;
        else 
            p_ZL16NTTTwiddleFactor_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL16NTTTwiddleFactor_2_address0 <= zext_ln101_1_fu_502_p1(17 - 1 downto 0);
    p_ZL16NTTTwiddleFactor_2_ce0 <= p_ZL16NTTTwiddleFactor_2_ce0_local;

    p_ZL16NTTTwiddleFactor_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            p_ZL16NTTTwiddleFactor_2_ce0_local <= ap_const_logic_1;
        else 
            p_ZL16NTTTwiddleFactor_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL16NTTTwiddleFactor_2_d0 <= gmem0_addr_read_reg_601;
    p_ZL16NTTTwiddleFactor_2_we0 <= p_ZL16NTTTwiddleFactor_2_we0_local;

    p_ZL16NTTTwiddleFactor_2_we0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001, trunc_ln99_reg_592_pp0_iter10_reg)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln99_reg_592_pp0_iter10_reg = ap_const_lv3_2) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            p_ZL16NTTTwiddleFactor_2_we0_local <= ap_const_logic_1;
        else 
            p_ZL16NTTTwiddleFactor_2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL16NTTTwiddleFactor_3_address0 <= zext_ln101_1_fu_502_p1(17 - 1 downto 0);
    p_ZL16NTTTwiddleFactor_3_ce0 <= p_ZL16NTTTwiddleFactor_3_ce0_local;

    p_ZL16NTTTwiddleFactor_3_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            p_ZL16NTTTwiddleFactor_3_ce0_local <= ap_const_logic_1;
        else 
            p_ZL16NTTTwiddleFactor_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL16NTTTwiddleFactor_3_d0 <= gmem0_addr_read_reg_601;
    p_ZL16NTTTwiddleFactor_3_we0 <= p_ZL16NTTTwiddleFactor_3_we0_local;

    p_ZL16NTTTwiddleFactor_3_we0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001, trunc_ln99_reg_592_pp0_iter10_reg)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln99_reg_592_pp0_iter10_reg = ap_const_lv3_3) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            p_ZL16NTTTwiddleFactor_3_we0_local <= ap_const_logic_1;
        else 
            p_ZL16NTTTwiddleFactor_3_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL16NTTTwiddleFactor_4_address0 <= zext_ln101_1_fu_502_p1(17 - 1 downto 0);
    p_ZL16NTTTwiddleFactor_4_ce0 <= p_ZL16NTTTwiddleFactor_4_ce0_local;

    p_ZL16NTTTwiddleFactor_4_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            p_ZL16NTTTwiddleFactor_4_ce0_local <= ap_const_logic_1;
        else 
            p_ZL16NTTTwiddleFactor_4_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL16NTTTwiddleFactor_4_d0 <= gmem0_addr_read_reg_601;
    p_ZL16NTTTwiddleFactor_4_we0 <= p_ZL16NTTTwiddleFactor_4_we0_local;

    p_ZL16NTTTwiddleFactor_4_we0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001, trunc_ln99_reg_592_pp0_iter10_reg)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln99_reg_592_pp0_iter10_reg = ap_const_lv3_4) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            p_ZL16NTTTwiddleFactor_4_we0_local <= ap_const_logic_1;
        else 
            p_ZL16NTTTwiddleFactor_4_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL16NTTTwiddleFactor_5_address0 <= zext_ln101_1_fu_502_p1(17 - 1 downto 0);
    p_ZL16NTTTwiddleFactor_5_ce0 <= p_ZL16NTTTwiddleFactor_5_ce0_local;

    p_ZL16NTTTwiddleFactor_5_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            p_ZL16NTTTwiddleFactor_5_ce0_local <= ap_const_logic_1;
        else 
            p_ZL16NTTTwiddleFactor_5_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL16NTTTwiddleFactor_5_d0 <= gmem0_addr_read_reg_601;
    p_ZL16NTTTwiddleFactor_5_we0 <= p_ZL16NTTTwiddleFactor_5_we0_local;

    p_ZL16NTTTwiddleFactor_5_we0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001, trunc_ln99_reg_592_pp0_iter10_reg)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln99_reg_592_pp0_iter10_reg = ap_const_lv3_5) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            p_ZL16NTTTwiddleFactor_5_we0_local <= ap_const_logic_1;
        else 
            p_ZL16NTTTwiddleFactor_5_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL16NTTTwiddleFactor_6_address0 <= zext_ln101_1_fu_502_p1(17 - 1 downto 0);
    p_ZL16NTTTwiddleFactor_6_ce0 <= p_ZL16NTTTwiddleFactor_6_ce0_local;

    p_ZL16NTTTwiddleFactor_6_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            p_ZL16NTTTwiddleFactor_6_ce0_local <= ap_const_logic_1;
        else 
            p_ZL16NTTTwiddleFactor_6_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL16NTTTwiddleFactor_6_d0 <= gmem0_addr_read_reg_601;
    p_ZL16NTTTwiddleFactor_6_we0 <= p_ZL16NTTTwiddleFactor_6_we0_local;

    p_ZL16NTTTwiddleFactor_6_we0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001, trunc_ln99_reg_592_pp0_iter10_reg)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln99_reg_592_pp0_iter10_reg = ap_const_lv3_6) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            p_ZL16NTTTwiddleFactor_6_we0_local <= ap_const_logic_1;
        else 
            p_ZL16NTTTwiddleFactor_6_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL16NTTTwiddleFactor_7_address0 <= zext_ln101_1_fu_502_p1(17 - 1 downto 0);
    p_ZL16NTTTwiddleFactor_7_ce0 <= p_ZL16NTTTwiddleFactor_7_ce0_local;

    p_ZL16NTTTwiddleFactor_7_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            p_ZL16NTTTwiddleFactor_7_ce0_local <= ap_const_logic_1;
        else 
            p_ZL16NTTTwiddleFactor_7_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL16NTTTwiddleFactor_7_d0 <= gmem0_addr_read_reg_601;
    p_ZL16NTTTwiddleFactor_7_we0 <= p_ZL16NTTTwiddleFactor_7_we0_local;

    p_ZL16NTTTwiddleFactor_7_we0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001, trunc_ln99_reg_592_pp0_iter10_reg)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln99_reg_592_pp0_iter10_reg = ap_const_lv3_7) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            p_ZL16NTTTwiddleFactor_7_we0_local <= ap_const_logic_1;
        else 
            p_ZL16NTTTwiddleFactor_7_we0_local <= ap_const_logic_0;
        end if; 
    end process;

        p_cast_cast_fu_455_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_cast_reg_581),64));

    select_ln97_1_fu_337_p3 <= 
        add_ln97_1_fu_307_p2 when (icmp_ln99_fu_313_p2(0) = '1') else 
        l_fu_128;
    select_ln97_fu_435_p3 <= 
        ap_const_lv6_0 when (icmp_ln99_reg_557(0) = '1') else 
        b_fu_120;
    select_ln99_1_fu_404_p3 <= 
        ap_const_lv19_1 when (icmp_ln99_fu_313_p2(0) = '1') else 
        add_ln99_1_fu_398_p2;
    select_ln99_fu_448_p3 <= 
        add_ln99_fu_442_p2 when (and_ln97_reg_562(0) = '1') else 
        select_ln97_fu_435_p3;
    t_mid2_fu_351_p3 <= 
        ap_const_lv13_0 when (empty_2310_fu_345_p2(0) = '1') else 
        t_fu_116;
    tmp_s_fu_479_p4 <= ((select_ln97_1_reg_567 & lshr_ln1_fu_469_p4) & ap_const_lv12_0);
    trunc_ln99_fu_465_p1 <= select_ln99_fu_448_p3(3 - 1 downto 0);
    xor_ln97_fu_319_p2 <= (icmp_ln99_fu_313_p2 xor ap_const_lv1_1);
    zext_ln101_1_fu_502_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln101_reg_596_pp0_iter10_reg),64));
    zext_ln101_fu_488_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(t_mid2_reg_572),17));
    zext_ln97_fu_373_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln_fu_365_p3),64));
end behav;
