// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module Compute_BConv_Compute_BConv_Pipeline_Systolic_Loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        cmp261_i_4,
        icmp42,
        cmp261_i_2,
        icmp,
        local_out_x_8_address1,
        local_out_x_8_ce1,
        local_out_x_8_we1,
        local_out_x_8_d1,
        local_out_x_7_address1,
        local_out_x_7_ce1,
        local_out_x_7_we1,
        local_out_x_7_d1,
        local_out_x_6_address1,
        local_out_x_6_ce1,
        local_out_x_6_we1,
        local_out_x_6_d1,
        local_out_x_5_address1,
        local_out_x_5_ce1,
        local_out_x_5_we1,
        local_out_x_5_d1,
        local_out_x_address1,
        local_out_x_ce1,
        local_out_x_we1,
        local_out_x_d1,
        local_in_x_address0,
        local_in_x_ce0,
        local_in_x_q0,
        local_in_x_3_address0,
        local_in_x_3_ce0,
        local_in_x_3_q0,
        local_in_x_4_address0,
        local_in_x_4_ce0,
        local_in_x_4_q0,
        p_reload116,
        mod_p_reload,
        p_reload139,
        p_reload140,
        p_reload117,
        mod_p_1_reload,
        p_reload141,
        p_reload142,
        p_reload118,
        mod_p_2_reload,
        p_reload143,
        p_reload144,
        p_reload119,
        p_reload147,
        p_reload145,
        p_reload146,
        p_reload115,
        mod_p_4_reload,
        p_reload137,
        p_reload138,
        p_reload121,
        p_reload122,
        p_reload123,
        p_reload124,
        p_reload120,
        p_reload111,
        p_reload112,
        p_reload113,
        p_reload114,
        p_reload,
        icmp_ln166
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [0:0] cmp261_i_4;
input  [0:0] icmp42;
input  [0:0] cmp261_i_2;
input  [0:0] icmp;
output  [11:0] local_out_x_8_address1;
output   local_out_x_8_ce1;
output   local_out_x_8_we1;
output  [63:0] local_out_x_8_d1;
output  [11:0] local_out_x_7_address1;
output   local_out_x_7_ce1;
output   local_out_x_7_we1;
output  [63:0] local_out_x_7_d1;
output  [11:0] local_out_x_6_address1;
output   local_out_x_6_ce1;
output   local_out_x_6_we1;
output  [63:0] local_out_x_6_d1;
output  [11:0] local_out_x_5_address1;
output   local_out_x_5_ce1;
output   local_out_x_5_we1;
output  [63:0] local_out_x_5_d1;
output  [11:0] local_out_x_address1;
output   local_out_x_ce1;
output   local_out_x_we1;
output  [63:0] local_out_x_d1;
output  [11:0] local_in_x_address0;
output   local_in_x_ce0;
input  [63:0] local_in_x_q0;
output  [11:0] local_in_x_3_address0;
output   local_in_x_3_ce0;
input  [63:0] local_in_x_3_q0;
output  [11:0] local_in_x_4_address0;
output   local_in_x_4_ce0;
input  [63:0] local_in_x_4_q0;
input  [63:0] p_reload116;
input  [63:0] mod_p_reload;
input  [63:0] p_reload139;
input  [63:0] p_reload140;
input  [63:0] p_reload117;
input  [63:0] mod_p_1_reload;
input  [63:0] p_reload141;
input  [63:0] p_reload142;
input  [63:0] p_reload118;
input  [63:0] mod_p_2_reload;
input  [63:0] p_reload143;
input  [63:0] p_reload144;
input  [63:0] p_reload119;
input  [63:0] p_reload147;
input  [63:0] p_reload145;
input  [63:0] p_reload146;
input  [63:0] p_reload115;
input  [63:0] mod_p_4_reload;
input  [63:0] p_reload137;
input  [63:0] p_reload138;
input  [63:0] p_reload121;
input  [63:0] p_reload122;
input  [63:0] p_reload123;
input  [63:0] p_reload124;
input  [63:0] p_reload120;
input  [63:0] p_reload111;
input  [63:0] p_reload112;
input  [63:0] p_reload113;
input  [63:0] p_reload114;
input  [63:0] p_reload;
input  [0:0] icmp_ln166;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln84_fu_1451_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln84_reg_3831;
reg   [0:0] icmp_ln84_reg_3831_pp0_iter1_reg;
reg   [0:0] icmp_ln84_reg_3831_pp0_iter2_reg;
reg   [0:0] icmp_ln84_reg_3831_pp0_iter3_reg;
reg   [0:0] icmp_ln84_reg_3831_pp0_iter4_reg;
reg   [0:0] icmp_ln84_reg_3831_pp0_iter5_reg;
reg   [0:0] icmp_ln84_reg_3831_pp0_iter6_reg;
reg   [0:0] icmp_ln84_reg_3831_pp0_iter7_reg;
reg   [0:0] icmp_ln84_reg_3831_pp0_iter8_reg;
reg   [0:0] icmp_ln84_reg_3831_pp0_iter9_reg;
reg   [0:0] icmp_ln84_reg_3831_pp0_iter10_reg;
reg   [0:0] icmp_ln84_reg_3831_pp0_iter11_reg;
reg   [0:0] icmp_ln84_reg_3831_pp0_iter12_reg;
reg   [0:0] icmp_ln84_reg_3831_pp0_iter13_reg;
reg   [0:0] icmp_ln84_reg_3831_pp0_iter14_reg;
reg   [0:0] icmp_ln84_reg_3831_pp0_iter15_reg;
reg   [0:0] icmp_ln84_reg_3831_pp0_iter16_reg;
reg   [0:0] tmp_reg_3835;
wire   [0:0] icmp_ln113_fu_1501_p2;
reg   [0:0] icmp_ln113_reg_3845;
wire   [0:0] icmp_ln113_1_fu_1528_p2;
reg   [0:0] icmp_ln113_1_reg_3855;
wire   [0:0] icmp_ln166_1_fu_1534_p2;
reg   [0:0] icmp_ln166_1_reg_3865;
reg   [0:0] icmp_ln166_1_reg_3865_pp0_iter1_reg;
reg   [0:0] icmp_ln166_1_reg_3865_pp0_iter2_reg;
reg   [0:0] icmp_ln166_1_reg_3865_pp0_iter3_reg;
reg   [0:0] icmp_ln166_1_reg_3865_pp0_iter4_reg;
reg   [0:0] icmp_ln166_1_reg_3865_pp0_iter5_reg;
reg   [0:0] icmp_ln166_1_reg_3865_pp0_iter6_reg;
reg   [0:0] icmp_ln166_1_reg_3865_pp0_iter7_reg;
reg   [0:0] icmp_ln166_1_reg_3865_pp0_iter8_reg;
reg   [0:0] icmp_ln166_1_reg_3865_pp0_iter9_reg;
reg   [0:0] icmp_ln166_1_reg_3865_pp0_iter10_reg;
reg   [0:0] icmp_ln166_1_reg_3865_pp0_iter11_reg;
reg   [0:0] icmp_ln166_1_reg_3865_pp0_iter12_reg;
reg   [0:0] icmp_ln166_1_reg_3865_pp0_iter13_reg;
reg   [0:0] icmp_ln166_1_reg_3865_pp0_iter14_reg;
reg   [0:0] icmp_ln166_1_reg_3865_pp0_iter15_reg;
reg   [0:0] icmp_ln166_1_reg_3865_pp0_iter16_reg;
wire   [0:0] icmp_ln166_3_fu_1550_p2;
reg   [0:0] icmp_ln166_3_reg_3870;
reg   [0:0] icmp_ln166_3_reg_3870_pp0_iter1_reg;
reg   [0:0] icmp_ln166_3_reg_3870_pp0_iter2_reg;
reg   [0:0] icmp_ln166_3_reg_3870_pp0_iter3_reg;
reg   [0:0] icmp_ln166_3_reg_3870_pp0_iter4_reg;
reg   [0:0] icmp_ln166_3_reg_3870_pp0_iter5_reg;
reg   [0:0] icmp_ln166_3_reg_3870_pp0_iter6_reg;
reg   [0:0] icmp_ln166_3_reg_3870_pp0_iter7_reg;
reg   [0:0] icmp_ln166_3_reg_3870_pp0_iter8_reg;
reg   [0:0] icmp_ln166_3_reg_3870_pp0_iter9_reg;
reg   [0:0] icmp_ln166_3_reg_3870_pp0_iter10_reg;
reg   [0:0] icmp_ln166_3_reg_3870_pp0_iter11_reg;
reg   [0:0] icmp_ln166_3_reg_3870_pp0_iter12_reg;
reg   [0:0] icmp_ln166_3_reg_3870_pp0_iter13_reg;
reg   [0:0] icmp_ln166_3_reg_3870_pp0_iter14_reg;
reg   [0:0] icmp_ln166_3_reg_3870_pp0_iter15_reg;
reg   [0:0] icmp_ln166_3_reg_3870_pp0_iter16_reg;
wire   [0:0] icmp_ln166_5_fu_1556_p2;
reg   [0:0] icmp_ln166_5_reg_3875;
reg   [0:0] icmp_ln166_5_reg_3875_pp0_iter1_reg;
reg   [0:0] icmp_ln166_5_reg_3875_pp0_iter2_reg;
reg   [0:0] icmp_ln166_5_reg_3875_pp0_iter3_reg;
reg   [0:0] icmp_ln166_5_reg_3875_pp0_iter4_reg;
reg   [0:0] icmp_ln166_5_reg_3875_pp0_iter5_reg;
reg   [0:0] icmp_ln166_5_reg_3875_pp0_iter6_reg;
reg   [0:0] icmp_ln166_5_reg_3875_pp0_iter7_reg;
reg   [0:0] icmp_ln166_5_reg_3875_pp0_iter8_reg;
reg   [0:0] icmp_ln166_5_reg_3875_pp0_iter9_reg;
reg   [0:0] icmp_ln166_5_reg_3875_pp0_iter10_reg;
reg   [0:0] icmp_ln166_5_reg_3875_pp0_iter11_reg;
reg   [0:0] icmp_ln166_5_reg_3875_pp0_iter12_reg;
reg   [0:0] icmp_ln166_5_reg_3875_pp0_iter13_reg;
reg   [0:0] icmp_ln166_5_reg_3875_pp0_iter14_reg;
reg   [0:0] icmp_ln166_5_reg_3875_pp0_iter15_reg;
reg   [0:0] icmp_ln166_5_reg_3875_pp0_iter16_reg;
wire   [0:0] icmp_ln166_7_fu_1562_p2;
reg   [0:0] icmp_ln166_7_reg_3880;
reg   [0:0] icmp_ln166_7_reg_3880_pp0_iter1_reg;
reg   [0:0] icmp_ln166_7_reg_3880_pp0_iter2_reg;
reg   [0:0] icmp_ln166_7_reg_3880_pp0_iter3_reg;
reg   [0:0] icmp_ln166_7_reg_3880_pp0_iter4_reg;
reg   [0:0] icmp_ln166_7_reg_3880_pp0_iter5_reg;
reg   [0:0] icmp_ln166_7_reg_3880_pp0_iter6_reg;
reg   [0:0] icmp_ln166_7_reg_3880_pp0_iter7_reg;
reg   [0:0] icmp_ln166_7_reg_3880_pp0_iter8_reg;
reg   [0:0] icmp_ln166_7_reg_3880_pp0_iter9_reg;
reg   [0:0] icmp_ln166_7_reg_3880_pp0_iter10_reg;
reg   [0:0] icmp_ln166_7_reg_3880_pp0_iter11_reg;
reg   [0:0] icmp_ln166_7_reg_3880_pp0_iter12_reg;
reg   [0:0] icmp_ln166_7_reg_3880_pp0_iter13_reg;
reg   [0:0] icmp_ln166_7_reg_3880_pp0_iter14_reg;
reg   [0:0] icmp_ln166_7_reg_3880_pp0_iter15_reg;
reg   [0:0] icmp_ln166_7_reg_3880_pp0_iter16_reg;
wire   [0:0] icmp_ln166_9_fu_1568_p2;
reg   [0:0] icmp_ln166_9_reg_3885;
reg   [0:0] icmp_ln166_9_reg_3885_pp0_iter1_reg;
reg   [0:0] icmp_ln166_9_reg_3885_pp0_iter2_reg;
reg   [0:0] icmp_ln166_9_reg_3885_pp0_iter3_reg;
reg   [0:0] icmp_ln166_9_reg_3885_pp0_iter4_reg;
reg   [0:0] icmp_ln166_9_reg_3885_pp0_iter5_reg;
reg   [0:0] icmp_ln166_9_reg_3885_pp0_iter6_reg;
reg   [0:0] icmp_ln166_9_reg_3885_pp0_iter7_reg;
reg   [0:0] icmp_ln166_9_reg_3885_pp0_iter8_reg;
reg   [0:0] icmp_ln166_9_reg_3885_pp0_iter9_reg;
reg   [0:0] icmp_ln166_9_reg_3885_pp0_iter10_reg;
reg   [0:0] icmp_ln166_9_reg_3885_pp0_iter11_reg;
reg   [0:0] icmp_ln166_9_reg_3885_pp0_iter12_reg;
reg   [0:0] icmp_ln166_9_reg_3885_pp0_iter13_reg;
reg   [0:0] icmp_ln166_9_reg_3885_pp0_iter14_reg;
reg   [0:0] icmp_ln166_9_reg_3885_pp0_iter15_reg;
reg   [0:0] icmp_ln166_9_reg_3885_pp0_iter16_reg;
reg   [31:0] inc280_i254_load_reg_3965;
reg   [31:0] inc280_i_1256_load_reg_3970;
reg   [31:0] inc280_i_2258_load_reg_3975;
reg   [31:0] inc280_i_3260_load_reg_3980;
reg   [31:0] inc280_i_4262_load_reg_3985;
wire   [63:0] sum_tmp_62_fu_2225_p3;
reg   [63:0] sum_tmp_62_reg_3990;
wire   [63:0] sum_tmp_64_fu_2255_p3;
reg   [63:0] sum_tmp_64_reg_3995;
wire   [63:0] sum_tmp_67_fu_2285_p3;
reg   [63:0] sum_tmp_67_reg_4000;
wire   [63:0] sum_tmp_69_fu_2315_p3;
reg   [63:0] sum_tmp_69_reg_4005;
wire   [63:0] sum_tmp_70_fu_2345_p3;
reg   [63:0] sum_tmp_70_reg_4010;
wire   [0:0] and_ln166_1_fu_2374_p2;
reg   [0:0] and_ln166_1_reg_4015;
wire   [0:0] and_ln166_3_fu_2411_p2;
reg   [0:0] and_ln166_3_reg_4019;
wire   [0:0] and_ln166_5_fu_2448_p2;
reg   [0:0] and_ln166_5_reg_4023;
wire   [0:0] and_ln166_7_fu_2485_p2;
reg   [0:0] and_ln166_7_reg_4027;
wire   [0:0] and_ln166_9_fu_2522_p2;
reg   [0:0] and_ln166_9_reg_4031;
reg    ap_condition_exit_pp0_iter17_stage0;
wire   [63:0] grp_MultMod_fu_858_ap_return;
wire   [63:0] grp_MultMod_fu_867_ap_return;
wire   [63:0] grp_MultMod_fu_876_ap_return;
wire   [63:0] grp_MultMod_fu_885_ap_return;
wire   [63:0] grp_MultMod_fu_894_ap_return;
wire   [63:0] grp_MultMod_fu_903_ap_return;
wire   [63:0] grp_MultMod_fu_912_ap_return;
wire   [63:0] grp_MultMod_fu_921_ap_return;
wire   [63:0] grp_MultMod_fu_930_ap_return;
wire   [63:0] grp_MultMod_fu_939_ap_return;
wire   [63:0] grp_MultMod_fu_948_ap_return;
wire   [63:0] grp_MultMod_fu_957_ap_return;
wire   [63:0] grp_MultMod_fu_966_ap_return;
wire   [63:0] grp_MultMod_fu_975_ap_return;
wire   [63:0] grp_MultMod_fu_984_ap_return;
wire    ap_block_pp0_stage0_ignoreCallOp297;
wire    ap_block_pp0_stage0_ignoreCallOp298;
wire    ap_block_pp0_stage0_ignoreCallOp299;
wire    ap_block_pp0_stage0_ignoreCallOp300;
wire    ap_block_pp0_stage0_ignoreCallOp301;
wire    ap_block_pp0_stage0_ignoreCallOp302;
wire    ap_block_pp0_stage0_ignoreCallOp303;
wire    ap_block_pp0_stage0_ignoreCallOp304;
wire    ap_block_pp0_stage0_ignoreCallOp305;
wire    ap_block_pp0_stage0_ignoreCallOp306;
wire    ap_block_pp0_stage0_ignoreCallOp307;
wire    ap_block_pp0_stage0_ignoreCallOp308;
wire    ap_block_pp0_stage0_ignoreCallOp309;
wire    ap_block_pp0_stage0_ignoreCallOp310;
wire    ap_block_pp0_stage0_ignoreCallOp311;
wire   [63:0] zext_ln84_fu_1463_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln113_fu_1486_p1;
wire   [63:0] zext_ln113_1_fu_1513_p1;
wire   [63:0] zext_ln168_fu_2933_p1;
wire   [63:0] zext_ln168_1_fu_2937_p1;
wire   [63:0] zext_ln168_2_fu_2941_p1;
wire   [63:0] zext_ln168_3_fu_2945_p1;
wire   [63:0] zext_ln168_4_fu_2949_p1;
reg   [63:0] x_in_fu_160;
wire   [63:0] empty_fu_1639_p3;
wire    ap_loop_init;
reg   [63:0] x_in_2_fu_164;
reg   [63:0] x_in_4_fu_168;
reg   [63:0] x_in_5_fu_172;
wire   [63:0] empty_47_fu_1646_p3;
reg   [63:0] x_in_7_fu_176;
reg   [63:0] x_in_9_fu_180;
reg   [63:0] x_in_10_fu_184;
wire   [63:0] empty_48_fu_1653_p3;
reg   [63:0] x_in_12_fu_188;
reg   [63:0] x_in_14_fu_192;
reg   [63:0] sum_in_fu_196;
wire   [63:0] sum_tmp_40_fu_1949_p3;
reg   [63:0] sum_in_5_fu_200;
wire   [63:0] sum_tmp_49_fu_2075_p3;
reg   [63:0] sum_in_1_fu_204;
wire   [63:0] sum_tmp_41_fu_1973_p3;
reg   [63:0] sum_in_6_fu_208;
wire   [63:0] sum_tmp_51_fu_2105_p3;
reg   [63:0] sum_in_2_fu_212;
wire   [63:0] sum_tmp_43_fu_1997_p3;
reg   [63:0] sum_in_7_fu_216;
wire   [63:0] sum_tmp_54_fu_2135_p3;
reg   [63:0] sum_in_3_fu_220;
wire   [63:0] sum_tmp_44_fu_2021_p3;
reg   [63:0] sum_in_8_fu_224;
wire   [63:0] sum_tmp_56_fu_2165_p3;
reg   [63:0] sum_in_4_fu_228;
wire   [63:0] sum_tmp_46_fu_2045_p3;
reg   [63:0] sum_in_9_fu_232;
wire   [63:0] sum_tmp_59_fu_2195_p3;
reg   [12:0] data_idx_fu_236;
wire   [12:0] add_ln84_fu_1457_p2;
reg   [12:0] ap_sig_allocacmp_t;
reg   [63:0] prod_pipe_fu_240;
reg   [63:0] prod_pipe_1_fu_244;
reg   [63:0] prod_pipe_2_fu_248;
reg   [63:0] prod_pipe_3_fu_252;
reg   [63:0] prod_pipe_4_fu_256;
reg   [63:0] prod_pipe_5_fu_260;
reg   [63:0] prod_pipe_6_fu_264;
reg   [63:0] prod_pipe_7_fu_268;
reg   [63:0] prod_pipe_8_fu_272;
reg   [63:0] prod_pipe_9_fu_276;
reg   [63:0] prod_pipe_10_fu_280;
reg   [63:0] prod_pipe_11_fu_284;
reg   [63:0] prod_pipe_12_fu_288;
reg   [63:0] prod_pipe_13_fu_292;
reg   [63:0] prod_pipe_14_fu_296;
reg   [63:0] sum_tmp_1_fu_300;
reg   [63:0] sum_tmp_2_fu_304;
reg   [63:0] sum_tmp_3_fu_308;
reg   [63:0] sum_tmp_4_fu_312;
reg   [63:0] sum_tmp_5_fu_316;
reg   [63:0] delayed_prod_fu_320;
reg   [63:0] delayed_prod_1_fu_324;
reg   [63:0] delayed_prod_2_fu_328;
reg   [63:0] delayed_prod_3_fu_332;
reg   [63:0] delayed_prod_4_fu_336;
reg   [63:0] delayed_prod_5_fu_340;
reg   [63:0] delayed_prod_6_fu_344;
reg   [63:0] delayed_prod_7_fu_348;
reg   [63:0] delayed_prod_8_fu_352;
reg   [63:0] delayed_prod_9_fu_356;
reg   [63:0] x_in_1_fu_360;
reg   [63:0] x_in_3_fu_364;
reg   [63:0] x_in_6_fu_368;
reg   [63:0] x_in_8_fu_372;
reg   [63:0] x_in_11_fu_376;
reg   [63:0] x_in_13_fu_380;
reg   [31:0] inc280_i254_fu_384;
wire   [31:0] add_ln169_fu_2379_p2;
reg   [31:0] inc280_i_1256_fu_388;
wire   [31:0] add_ln169_1_fu_2416_p2;
reg   [31:0] inc280_i_2258_fu_392;
wire   [31:0] add_ln169_2_fu_2453_p2;
reg   [31:0] inc280_i_3260_fu_396;
wire   [31:0] add_ln169_3_fu_2490_p2;
reg   [31:0] inc280_i_4262_fu_400;
wire   [31:0] add_ln169_4_fu_2527_p2;
reg   [63:0] prod_pipe_15_fu_404;
reg   [63:0] prod_pipe_16_fu_408;
reg   [63:0] prod_pipe_17_fu_412;
reg   [63:0] prod_pipe_18_fu_416;
reg   [63:0] prod_pipe_19_fu_420;
reg   [63:0] prod_pipe_20_fu_424;
reg   [63:0] prod_pipe_21_fu_428;
reg   [63:0] prod_pipe_22_fu_432;
reg   [63:0] prod_pipe_23_fu_436;
reg   [63:0] prod_pipe_24_fu_440;
reg   [63:0] prod_pipe_25_fu_444;
reg   [63:0] prod_pipe_26_fu_448;
reg   [63:0] prod_pipe_27_fu_452;
reg   [63:0] prod_pipe_28_fu_456;
reg   [63:0] prod_pipe_29_fu_460;
reg   [63:0] prod_pipe_30_fu_464;
reg   [63:0] prod_pipe_31_fu_468;
reg   [63:0] prod_pipe_32_fu_472;
reg   [63:0] prod_pipe_33_fu_476;
reg   [63:0] prod_pipe_34_fu_480;
reg   [63:0] prod_pipe_35_fu_484;
reg   [63:0] prod_pipe_36_fu_488;
reg   [63:0] prod_pipe_37_fu_492;
reg   [63:0] prod_pipe_38_fu_496;
reg   [63:0] prod_pipe_39_fu_500;
reg   [63:0] prod_pipe_40_fu_504;
reg   [63:0] prod_pipe_41_fu_508;
reg   [63:0] prod_pipe_42_fu_512;
reg   [63:0] prod_pipe_43_fu_516;
reg   [63:0] prod_pipe_44_fu_520;
reg    local_in_x_ce0_local;
reg    local_in_x_3_ce0_local;
reg    local_in_x_4_ce0_local;
reg    local_out_x_we1_local;
reg    local_out_x_ce1_local;
reg    local_out_x_5_we1_local;
reg    local_out_x_5_ce1_local;
reg    local_out_x_6_we1_local;
reg    local_out_x_6_ce1_local;
reg    local_out_x_7_we1_local;
reg    local_out_x_7_ce1_local;
reg    local_out_x_8_we1_local;
reg    local_out_x_8_ce1_local;
wire   [13:0] zext_ln84_1_fu_1468_p1;
wire   [13:0] add_ln112_fu_1480_p2;
wire   [1:0] tmp_1_fu_1491_p4;
wire   [13:0] add_ln112_1_fu_1507_p2;
wire   [1:0] tmp_2_fu_1518_p4;
wire   [9:0] tmp_4_fu_1540_p4;
wire   [0:0] icmp_ln155_fu_1933_p2;
wire   [0:0] xor_ln155_fu_1938_p2;
wire   [63:0] sum_tmp_39_fu_1944_p2;
wire   [0:0] icmp_ln155_1_fu_1957_p2;
wire   [0:0] xor_ln155_1_fu_1962_p2;
wire   [63:0] sub_ln155_1_fu_1968_p2;
wire   [0:0] icmp_ln155_2_fu_1981_p2;
wire   [0:0] xor_ln155_2_fu_1986_p2;
wire   [63:0] sum_tmp_42_fu_1992_p2;
wire   [0:0] icmp_ln155_3_fu_2005_p2;
wire   [0:0] xor_ln155_3_fu_2010_p2;
wire   [63:0] sub_ln155_3_fu_2016_p2;
wire   [0:0] icmp_ln155_4_fu_2029_p2;
wire   [0:0] xor_ln155_4_fu_2034_p2;
wire   [63:0] sum_tmp_45_fu_2040_p2;
wire   [63:0] sum_tmp_47_fu_2053_p2;
wire   [0:0] icmp_ln155_5_fu_2059_p2;
wire   [0:0] xor_ln155_5_fu_2064_p2;
wire   [63:0] sum_tmp_48_fu_2070_p2;
wire   [63:0] sum_tmp_50_fu_2083_p2;
wire   [0:0] icmp_ln155_6_fu_2089_p2;
wire   [0:0] xor_ln155_6_fu_2094_p2;
wire   [63:0] sub_ln155_6_fu_2100_p2;
wire   [63:0] sum_tmp_52_fu_2113_p2;
wire   [0:0] icmp_ln155_7_fu_2119_p2;
wire   [0:0] xor_ln155_7_fu_2124_p2;
wire   [63:0] sum_tmp_53_fu_2130_p2;
wire   [63:0] sum_tmp_55_fu_2143_p2;
wire   [0:0] icmp_ln155_8_fu_2149_p2;
wire   [0:0] xor_ln155_8_fu_2154_p2;
wire   [63:0] sub_ln155_8_fu_2160_p2;
wire   [63:0] sum_tmp_57_fu_2173_p2;
wire   [0:0] icmp_ln155_9_fu_2179_p2;
wire   [0:0] xor_ln155_9_fu_2184_p2;
wire   [63:0] sum_tmp_58_fu_2190_p2;
wire   [63:0] sum_tmp_60_fu_2203_p2;
wire   [0:0] icmp_ln155_10_fu_2209_p2;
wire   [0:0] xor_ln155_10_fu_2214_p2;
wire   [63:0] sum_tmp_61_fu_2220_p2;
wire   [63:0] sum_tmp_63_fu_2233_p2;
wire   [0:0] icmp_ln155_11_fu_2239_p2;
wire   [0:0] xor_ln155_11_fu_2244_p2;
wire   [63:0] sub_ln155_11_fu_2250_p2;
wire   [63:0] sum_tmp_65_fu_2263_p2;
wire   [0:0] icmp_ln155_12_fu_2269_p2;
wire   [0:0] xor_ln155_12_fu_2274_p2;
wire   [63:0] sum_tmp_66_fu_2280_p2;
wire   [63:0] sum_tmp_68_fu_2293_p2;
wire   [0:0] icmp_ln155_13_fu_2299_p2;
wire   [0:0] xor_ln155_13_fu_2304_p2;
wire   [63:0] sub_ln155_13_fu_2310_p2;
wire   [63:0] sum_tmp_fu_2323_p2;
wire   [0:0] icmp_ln155_14_fu_2329_p2;
wire   [0:0] xor_ln155_14_fu_2334_p2;
wire   [63:0] sum_tmp_37_fu_2340_p2;
wire   [19:0] tmp_3_fu_2353_p4;
wire   [0:0] icmp_ln166_2_fu_2363_p2;
wire   [0:0] and_ln166_fu_2369_p2;
wire   [19:0] tmp_5_fu_2390_p4;
wire   [0:0] icmp_ln166_4_fu_2400_p2;
wire   [0:0] and_ln166_2_fu_2406_p2;
wire   [19:0] tmp_6_fu_2427_p4;
wire   [0:0] icmp_ln166_6_fu_2437_p2;
wire   [0:0] and_ln166_4_fu_2443_p2;
wire   [19:0] tmp_7_fu_2464_p4;
wire   [0:0] icmp_ln166_8_fu_2474_p2;
wire   [0:0] and_ln166_6_fu_2480_p2;
wire   [19:0] tmp_8_fu_2501_p4;
wire   [0:0] icmp_ln166_10_fu_2511_p2;
wire   [0:0] and_ln166_8_fu_2517_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_3837;
reg    ap_condition_3841;
reg    ap_condition_3845;
reg    ap_condition_3849;
reg    ap_condition_3853;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 x_in_fu_160 = 64'd0;
#0 x_in_2_fu_164 = 64'd0;
#0 x_in_4_fu_168 = 64'd0;
#0 x_in_5_fu_172 = 64'd0;
#0 x_in_7_fu_176 = 64'd0;
#0 x_in_9_fu_180 = 64'd0;
#0 x_in_10_fu_184 = 64'd0;
#0 x_in_12_fu_188 = 64'd0;
#0 x_in_14_fu_192 = 64'd0;
#0 sum_in_fu_196 = 64'd0;
#0 sum_in_5_fu_200 = 64'd0;
#0 sum_in_1_fu_204 = 64'd0;
#0 sum_in_6_fu_208 = 64'd0;
#0 sum_in_2_fu_212 = 64'd0;
#0 sum_in_7_fu_216 = 64'd0;
#0 sum_in_3_fu_220 = 64'd0;
#0 sum_in_8_fu_224 = 64'd0;
#0 sum_in_4_fu_228 = 64'd0;
#0 sum_in_9_fu_232 = 64'd0;
#0 data_idx_fu_236 = 13'd0;
#0 prod_pipe_fu_240 = 64'd0;
#0 prod_pipe_1_fu_244 = 64'd0;
#0 prod_pipe_2_fu_248 = 64'd0;
#0 prod_pipe_3_fu_252 = 64'd0;
#0 prod_pipe_4_fu_256 = 64'd0;
#0 prod_pipe_5_fu_260 = 64'd0;
#0 prod_pipe_6_fu_264 = 64'd0;
#0 prod_pipe_7_fu_268 = 64'd0;
#0 prod_pipe_8_fu_272 = 64'd0;
#0 prod_pipe_9_fu_276 = 64'd0;
#0 prod_pipe_10_fu_280 = 64'd0;
#0 prod_pipe_11_fu_284 = 64'd0;
#0 prod_pipe_12_fu_288 = 64'd0;
#0 prod_pipe_13_fu_292 = 64'd0;
#0 prod_pipe_14_fu_296 = 64'd0;
#0 sum_tmp_1_fu_300 = 64'd0;
#0 sum_tmp_2_fu_304 = 64'd0;
#0 sum_tmp_3_fu_308 = 64'd0;
#0 sum_tmp_4_fu_312 = 64'd0;
#0 sum_tmp_5_fu_316 = 64'd0;
#0 delayed_prod_fu_320 = 64'd0;
#0 delayed_prod_1_fu_324 = 64'd0;
#0 delayed_prod_2_fu_328 = 64'd0;
#0 delayed_prod_3_fu_332 = 64'd0;
#0 delayed_prod_4_fu_336 = 64'd0;
#0 delayed_prod_5_fu_340 = 64'd0;
#0 delayed_prod_6_fu_344 = 64'd0;
#0 delayed_prod_7_fu_348 = 64'd0;
#0 delayed_prod_8_fu_352 = 64'd0;
#0 delayed_prod_9_fu_356 = 64'd0;
#0 x_in_1_fu_360 = 64'd0;
#0 x_in_3_fu_364 = 64'd0;
#0 x_in_6_fu_368 = 64'd0;
#0 x_in_8_fu_372 = 64'd0;
#0 x_in_11_fu_376 = 64'd0;
#0 x_in_13_fu_380 = 64'd0;
#0 inc280_i254_fu_384 = 32'd0;
#0 inc280_i_1256_fu_388 = 32'd0;
#0 inc280_i_2258_fu_392 = 32'd0;
#0 inc280_i_3260_fu_396 = 32'd0;
#0 inc280_i_4262_fu_400 = 32'd0;
#0 prod_pipe_15_fu_404 = 64'd0;
#0 prod_pipe_16_fu_408 = 64'd0;
#0 prod_pipe_17_fu_412 = 64'd0;
#0 prod_pipe_18_fu_416 = 64'd0;
#0 prod_pipe_19_fu_420 = 64'd0;
#0 prod_pipe_20_fu_424 = 64'd0;
#0 prod_pipe_21_fu_428 = 64'd0;
#0 prod_pipe_22_fu_432 = 64'd0;
#0 prod_pipe_23_fu_436 = 64'd0;
#0 prod_pipe_24_fu_440 = 64'd0;
#0 prod_pipe_25_fu_444 = 64'd0;
#0 prod_pipe_26_fu_448 = 64'd0;
#0 prod_pipe_27_fu_452 = 64'd0;
#0 prod_pipe_28_fu_456 = 64'd0;
#0 prod_pipe_29_fu_460 = 64'd0;
#0 prod_pipe_30_fu_464 = 64'd0;
#0 prod_pipe_31_fu_468 = 64'd0;
#0 prod_pipe_32_fu_472 = 64'd0;
#0 prod_pipe_33_fu_476 = 64'd0;
#0 prod_pipe_34_fu_480 = 64'd0;
#0 prod_pipe_35_fu_484 = 64'd0;
#0 prod_pipe_36_fu_488 = 64'd0;
#0 prod_pipe_37_fu_492 = 64'd0;
#0 prod_pipe_38_fu_496 = 64'd0;
#0 prod_pipe_39_fu_500 = 64'd0;
#0 prod_pipe_40_fu_504 = 64'd0;
#0 prod_pipe_41_fu_508 = 64'd0;
#0 prod_pipe_42_fu_512 = 64'd0;
#0 prod_pipe_43_fu_516 = 64'd0;
#0 prod_pipe_44_fu_520 = 64'd0;
#0 ap_done_reg = 1'b0;
end

Compute_BConv_MultMod grp_MultMod_fu_858(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .a_val(x_in_fu_160),
    .b_val(p_reload116),
    .mod_val(mod_p_reload),
    .m_val(p_reload139),
    .k_half_val(p_reload140),
    .ap_return(grp_MultMod_fu_858_ap_return)
);

Compute_BConv_MultMod grp_MultMod_fu_867(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .a_val(x_in_1_fu_360),
    .b_val(p_reload117),
    .mod_val(mod_p_1_reload),
    .m_val(p_reload141),
    .k_half_val(p_reload142),
    .ap_return(grp_MultMod_fu_867_ap_return)
);

Compute_BConv_MultMod grp_MultMod_fu_876(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .a_val(x_in_2_fu_164),
    .b_val(p_reload118),
    .mod_val(mod_p_2_reload),
    .m_val(p_reload143),
    .k_half_val(p_reload144),
    .ap_return(grp_MultMod_fu_876_ap_return)
);

Compute_BConv_MultMod grp_MultMod_fu_885(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .a_val(x_in_3_fu_364),
    .b_val(p_reload119),
    .mod_val(p_reload147),
    .m_val(p_reload145),
    .k_half_val(p_reload146),
    .ap_return(grp_MultMod_fu_885_ap_return)
);

Compute_BConv_MultMod grp_MultMod_fu_894(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .a_val(x_in_4_fu_168),
    .b_val(p_reload115),
    .mod_val(mod_p_4_reload),
    .m_val(p_reload137),
    .k_half_val(p_reload138),
    .ap_return(grp_MultMod_fu_894_ap_return)
);

Compute_BConv_MultMod grp_MultMod_fu_903(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .a_val(x_in_5_fu_172),
    .b_val(p_reload121),
    .mod_val(mod_p_reload),
    .m_val(p_reload139),
    .k_half_val(p_reload140),
    .ap_return(grp_MultMod_fu_903_ap_return)
);

Compute_BConv_MultMod grp_MultMod_fu_912(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .a_val(x_in_6_fu_368),
    .b_val(p_reload122),
    .mod_val(mod_p_1_reload),
    .m_val(p_reload141),
    .k_half_val(p_reload142),
    .ap_return(grp_MultMod_fu_912_ap_return)
);

Compute_BConv_MultMod grp_MultMod_fu_921(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .a_val(x_in_7_fu_176),
    .b_val(p_reload123),
    .mod_val(mod_p_2_reload),
    .m_val(p_reload143),
    .k_half_val(p_reload144),
    .ap_return(grp_MultMod_fu_921_ap_return)
);

Compute_BConv_MultMod grp_MultMod_fu_930(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .a_val(x_in_8_fu_372),
    .b_val(p_reload124),
    .mod_val(p_reload147),
    .m_val(p_reload145),
    .k_half_val(p_reload146),
    .ap_return(grp_MultMod_fu_930_ap_return)
);

Compute_BConv_MultMod grp_MultMod_fu_939(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .a_val(x_in_9_fu_180),
    .b_val(p_reload120),
    .mod_val(mod_p_4_reload),
    .m_val(p_reload137),
    .k_half_val(p_reload138),
    .ap_return(grp_MultMod_fu_939_ap_return)
);

Compute_BConv_MultMod grp_MultMod_fu_948(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .a_val(x_in_10_fu_184),
    .b_val(p_reload111),
    .mod_val(mod_p_reload),
    .m_val(p_reload139),
    .k_half_val(p_reload140),
    .ap_return(grp_MultMod_fu_948_ap_return)
);

Compute_BConv_MultMod grp_MultMod_fu_957(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .a_val(x_in_11_fu_376),
    .b_val(p_reload112),
    .mod_val(mod_p_1_reload),
    .m_val(p_reload141),
    .k_half_val(p_reload142),
    .ap_return(grp_MultMod_fu_957_ap_return)
);

Compute_BConv_MultMod grp_MultMod_fu_966(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .a_val(x_in_12_fu_188),
    .b_val(p_reload113),
    .mod_val(mod_p_2_reload),
    .m_val(p_reload143),
    .k_half_val(p_reload144),
    .ap_return(grp_MultMod_fu_966_ap_return)
);

Compute_BConv_MultMod grp_MultMod_fu_975(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .a_val(x_in_13_fu_380),
    .b_val(p_reload114),
    .mod_val(p_reload147),
    .m_val(p_reload145),
    .k_half_val(p_reload146),
    .ap_return(grp_MultMod_fu_975_ap_return)
);

Compute_BConv_MultMod grp_MultMod_fu_984(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .a_val(x_in_14_fu_192),
    .b_val(p_reload),
    .mod_val(mod_p_4_reload),
    .m_val(p_reload137),
    .k_half_val(p_reload138),
    .ap_return(grp_MultMod_fu_984_ap_return)
);

Compute_BConv_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter17_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter17_stage0)) begin
            ap_enable_reg_pp0_iter18 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln84_fu_1451_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            data_idx_fu_236 <= add_ln84_fu_1457_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            data_idx_fu_236 <= 13'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            delayed_prod_1_fu_324 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            delayed_prod_1_fu_324 <= prod_pipe_21_fu_428;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            delayed_prod_2_fu_328 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            delayed_prod_2_fu_328 <= prod_pipe_22_fu_432;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            delayed_prod_3_fu_332 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            delayed_prod_3_fu_332 <= prod_pipe_23_fu_436;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            delayed_prod_4_fu_336 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            delayed_prod_4_fu_336 <= prod_pipe_24_fu_440;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            delayed_prod_5_fu_340 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            delayed_prod_5_fu_340 <= prod_pipe_25_fu_444;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            delayed_prod_6_fu_344 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            delayed_prod_6_fu_344 <= prod_pipe_26_fu_448;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            delayed_prod_7_fu_348 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            delayed_prod_7_fu_348 <= prod_pipe_27_fu_452;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            delayed_prod_8_fu_352 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            delayed_prod_8_fu_352 <= prod_pipe_28_fu_456;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            delayed_prod_9_fu_356 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            delayed_prod_9_fu_356 <= prod_pipe_29_fu_460;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            delayed_prod_fu_320 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            delayed_prod_fu_320 <= prod_pipe_20_fu_424;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            inc280_i254_fu_384 <= 32'd0;
        end else if ((1'b1 == ap_condition_3837)) begin
            inc280_i254_fu_384 <= add_ln169_fu_2379_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            inc280_i_1256_fu_388 <= 32'd0;
        end else if ((1'b1 == ap_condition_3841)) begin
            inc280_i_1256_fu_388 <= add_ln169_1_fu_2416_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            inc280_i_2258_fu_392 <= 32'd0;
        end else if ((1'b1 == ap_condition_3845)) begin
            inc280_i_2258_fu_392 <= add_ln169_2_fu_2453_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            inc280_i_3260_fu_396 <= 32'd0;
        end else if ((1'b1 == ap_condition_3849)) begin
            inc280_i_3260_fu_396 <= add_ln169_3_fu_2490_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            inc280_i_4262_fu_400 <= 32'd0;
        end else if ((1'b1 == ap_condition_3853)) begin
            inc280_i_4262_fu_400 <= add_ln169_4_fu_2527_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            prod_pipe_10_fu_280 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            prod_pipe_10_fu_280 <= prod_pipe_40_fu_504;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            prod_pipe_11_fu_284 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            prod_pipe_11_fu_284 <= prod_pipe_41_fu_508;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            prod_pipe_12_fu_288 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            prod_pipe_12_fu_288 <= prod_pipe_42_fu_512;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            prod_pipe_13_fu_292 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            prod_pipe_13_fu_292 <= prod_pipe_43_fu_516;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            prod_pipe_14_fu_296 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            prod_pipe_14_fu_296 <= prod_pipe_44_fu_520;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            prod_pipe_15_fu_404 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            prod_pipe_15_fu_404 <= prod_pipe_fu_240;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            prod_pipe_16_fu_408 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            prod_pipe_16_fu_408 <= prod_pipe_1_fu_244;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            prod_pipe_17_fu_412 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            prod_pipe_17_fu_412 <= prod_pipe_2_fu_248;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            prod_pipe_18_fu_416 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            prod_pipe_18_fu_416 <= prod_pipe_3_fu_252;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            prod_pipe_19_fu_420 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            prod_pipe_19_fu_420 <= prod_pipe_4_fu_256;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            prod_pipe_1_fu_244 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            prod_pipe_1_fu_244 <= prod_pipe_31_fu_468;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            prod_pipe_20_fu_424 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            prod_pipe_20_fu_424 <= prod_pipe_5_fu_260;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            prod_pipe_21_fu_428 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            prod_pipe_21_fu_428 <= prod_pipe_6_fu_264;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            prod_pipe_22_fu_432 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            prod_pipe_22_fu_432 <= prod_pipe_7_fu_268;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            prod_pipe_23_fu_436 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            prod_pipe_23_fu_436 <= prod_pipe_8_fu_272;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            prod_pipe_24_fu_440 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            prod_pipe_24_fu_440 <= prod_pipe_9_fu_276;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            prod_pipe_25_fu_444 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            prod_pipe_25_fu_444 <= prod_pipe_10_fu_280;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            prod_pipe_26_fu_448 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            prod_pipe_26_fu_448 <= prod_pipe_11_fu_284;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            prod_pipe_27_fu_452 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            prod_pipe_27_fu_452 <= prod_pipe_12_fu_288;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            prod_pipe_28_fu_456 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            prod_pipe_28_fu_456 <= prod_pipe_13_fu_292;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            prod_pipe_29_fu_460 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            prod_pipe_29_fu_460 <= prod_pipe_14_fu_296;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            prod_pipe_2_fu_248 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            prod_pipe_2_fu_248 <= prod_pipe_32_fu_472;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            prod_pipe_30_fu_464 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            prod_pipe_30_fu_464 <= grp_MultMod_fu_858_ap_return;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            prod_pipe_31_fu_468 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            prod_pipe_31_fu_468 <= grp_MultMod_fu_867_ap_return;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            prod_pipe_32_fu_472 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            prod_pipe_32_fu_472 <= grp_MultMod_fu_876_ap_return;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            prod_pipe_33_fu_476 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            prod_pipe_33_fu_476 <= grp_MultMod_fu_885_ap_return;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            prod_pipe_34_fu_480 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            prod_pipe_34_fu_480 <= grp_MultMod_fu_894_ap_return;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            prod_pipe_35_fu_484 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            prod_pipe_35_fu_484 <= grp_MultMod_fu_903_ap_return;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            prod_pipe_36_fu_488 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            prod_pipe_36_fu_488 <= grp_MultMod_fu_912_ap_return;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            prod_pipe_37_fu_492 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            prod_pipe_37_fu_492 <= grp_MultMod_fu_921_ap_return;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            prod_pipe_38_fu_496 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            prod_pipe_38_fu_496 <= grp_MultMod_fu_930_ap_return;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            prod_pipe_39_fu_500 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            prod_pipe_39_fu_500 <= grp_MultMod_fu_939_ap_return;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            prod_pipe_3_fu_252 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            prod_pipe_3_fu_252 <= prod_pipe_33_fu_476;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            prod_pipe_40_fu_504 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            prod_pipe_40_fu_504 <= grp_MultMod_fu_948_ap_return;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            prod_pipe_41_fu_508 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            prod_pipe_41_fu_508 <= grp_MultMod_fu_957_ap_return;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            prod_pipe_42_fu_512 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            prod_pipe_42_fu_512 <= grp_MultMod_fu_966_ap_return;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            prod_pipe_43_fu_516 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            prod_pipe_43_fu_516 <= grp_MultMod_fu_975_ap_return;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            prod_pipe_44_fu_520 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            prod_pipe_44_fu_520 <= grp_MultMod_fu_984_ap_return;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            prod_pipe_4_fu_256 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            prod_pipe_4_fu_256 <= prod_pipe_34_fu_480;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            prod_pipe_5_fu_260 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            prod_pipe_5_fu_260 <= prod_pipe_35_fu_484;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            prod_pipe_6_fu_264 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            prod_pipe_6_fu_264 <= prod_pipe_36_fu_488;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            prod_pipe_7_fu_268 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            prod_pipe_7_fu_268 <= prod_pipe_37_fu_492;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            prod_pipe_8_fu_272 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            prod_pipe_8_fu_272 <= prod_pipe_38_fu_496;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            prod_pipe_9_fu_276 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            prod_pipe_9_fu_276 <= prod_pipe_39_fu_500;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            prod_pipe_fu_240 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            prod_pipe_fu_240 <= prod_pipe_30_fu_464;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            sum_in_1_fu_204 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            sum_in_1_fu_204 <= sum_tmp_41_fu_1973_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            sum_in_2_fu_212 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            sum_in_2_fu_212 <= sum_tmp_43_fu_1997_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            sum_in_3_fu_220 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            sum_in_3_fu_220 <= sum_tmp_44_fu_2021_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            sum_in_4_fu_228 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            sum_in_4_fu_228 <= sum_tmp_46_fu_2045_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            sum_in_5_fu_200 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            sum_in_5_fu_200 <= sum_tmp_49_fu_2075_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            sum_in_6_fu_208 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            sum_in_6_fu_208 <= sum_tmp_51_fu_2105_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            sum_in_7_fu_216 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            sum_in_7_fu_216 <= sum_tmp_54_fu_2135_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            sum_in_8_fu_224 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            sum_in_8_fu_224 <= sum_tmp_56_fu_2165_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            sum_in_9_fu_232 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            sum_in_9_fu_232 <= sum_tmp_59_fu_2195_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            sum_in_fu_196 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            sum_in_fu_196 <= sum_tmp_40_fu_1949_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            sum_tmp_1_fu_300 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            sum_tmp_1_fu_300 <= prod_pipe_15_fu_404;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            sum_tmp_2_fu_304 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            sum_tmp_2_fu_304 <= prod_pipe_16_fu_408;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            sum_tmp_3_fu_308 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            sum_tmp_3_fu_308 <= prod_pipe_17_fu_412;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            sum_tmp_4_fu_312 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            sum_tmp_4_fu_312 <= prod_pipe_18_fu_416;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            sum_tmp_5_fu_316 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0))) begin
            sum_tmp_5_fu_316 <= prod_pipe_19_fu_420;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            x_in_10_fu_184 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln84_reg_3831 == 1'd0))) begin
            x_in_10_fu_184 <= empty_48_fu_1653_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            x_in_11_fu_376 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln84_reg_3831 == 1'd0))) begin
            x_in_11_fu_376 <= x_in_10_fu_184;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            x_in_12_fu_188 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln84_reg_3831 == 1'd0))) begin
            x_in_12_fu_188 <= x_in_11_fu_376;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            x_in_13_fu_380 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln84_reg_3831 == 1'd0))) begin
            x_in_13_fu_380 <= x_in_12_fu_188;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            x_in_14_fu_192 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln84_reg_3831 == 1'd0))) begin
            x_in_14_fu_192 <= x_in_13_fu_380;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            x_in_1_fu_360 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln84_reg_3831 == 1'd0))) begin
            x_in_1_fu_360 <= x_in_fu_160;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            x_in_2_fu_164 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln84_reg_3831 == 1'd0))) begin
            x_in_2_fu_164 <= x_in_1_fu_360;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            x_in_3_fu_364 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln84_reg_3831 == 1'd0))) begin
            x_in_3_fu_364 <= x_in_2_fu_164;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            x_in_4_fu_168 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln84_reg_3831 == 1'd0))) begin
            x_in_4_fu_168 <= x_in_3_fu_364;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            x_in_5_fu_172 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln84_reg_3831 == 1'd0))) begin
            x_in_5_fu_172 <= empty_47_fu_1646_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            x_in_6_fu_368 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln84_reg_3831 == 1'd0))) begin
            x_in_6_fu_368 <= x_in_5_fu_172;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            x_in_7_fu_176 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln84_reg_3831 == 1'd0))) begin
            x_in_7_fu_176 <= x_in_6_fu_368;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            x_in_8_fu_372 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln84_reg_3831 == 1'd0))) begin
            x_in_8_fu_372 <= x_in_7_fu_176;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            x_in_9_fu_180 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln84_reg_3831 == 1'd0))) begin
            x_in_9_fu_180 <= x_in_8_fu_372;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            x_in_fu_160 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln84_reg_3831 == 1'd0))) begin
            x_in_fu_160 <= empty_fu_1639_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        and_ln166_1_reg_4015 <= and_ln166_1_fu_2374_p2;
        and_ln166_3_reg_4019 <= and_ln166_3_fu_2411_p2;
        and_ln166_5_reg_4023 <= and_ln166_5_fu_2448_p2;
        and_ln166_7_reg_4027 <= and_ln166_7_fu_2485_p2;
        and_ln166_9_reg_4031 <= and_ln166_9_fu_2522_p2;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        icmp_ln166_1_reg_3865_pp0_iter10_reg <= icmp_ln166_1_reg_3865_pp0_iter9_reg;
        icmp_ln166_1_reg_3865_pp0_iter11_reg <= icmp_ln166_1_reg_3865_pp0_iter10_reg;
        icmp_ln166_1_reg_3865_pp0_iter12_reg <= icmp_ln166_1_reg_3865_pp0_iter11_reg;
        icmp_ln166_1_reg_3865_pp0_iter13_reg <= icmp_ln166_1_reg_3865_pp0_iter12_reg;
        icmp_ln166_1_reg_3865_pp0_iter14_reg <= icmp_ln166_1_reg_3865_pp0_iter13_reg;
        icmp_ln166_1_reg_3865_pp0_iter15_reg <= icmp_ln166_1_reg_3865_pp0_iter14_reg;
        icmp_ln166_1_reg_3865_pp0_iter16_reg <= icmp_ln166_1_reg_3865_pp0_iter15_reg;
        icmp_ln166_1_reg_3865_pp0_iter2_reg <= icmp_ln166_1_reg_3865_pp0_iter1_reg;
        icmp_ln166_1_reg_3865_pp0_iter3_reg <= icmp_ln166_1_reg_3865_pp0_iter2_reg;
        icmp_ln166_1_reg_3865_pp0_iter4_reg <= icmp_ln166_1_reg_3865_pp0_iter3_reg;
        icmp_ln166_1_reg_3865_pp0_iter5_reg <= icmp_ln166_1_reg_3865_pp0_iter4_reg;
        icmp_ln166_1_reg_3865_pp0_iter6_reg <= icmp_ln166_1_reg_3865_pp0_iter5_reg;
        icmp_ln166_1_reg_3865_pp0_iter7_reg <= icmp_ln166_1_reg_3865_pp0_iter6_reg;
        icmp_ln166_1_reg_3865_pp0_iter8_reg <= icmp_ln166_1_reg_3865_pp0_iter7_reg;
        icmp_ln166_1_reg_3865_pp0_iter9_reg <= icmp_ln166_1_reg_3865_pp0_iter8_reg;
        icmp_ln166_3_reg_3870_pp0_iter10_reg <= icmp_ln166_3_reg_3870_pp0_iter9_reg;
        icmp_ln166_3_reg_3870_pp0_iter11_reg <= icmp_ln166_3_reg_3870_pp0_iter10_reg;
        icmp_ln166_3_reg_3870_pp0_iter12_reg <= icmp_ln166_3_reg_3870_pp0_iter11_reg;
        icmp_ln166_3_reg_3870_pp0_iter13_reg <= icmp_ln166_3_reg_3870_pp0_iter12_reg;
        icmp_ln166_3_reg_3870_pp0_iter14_reg <= icmp_ln166_3_reg_3870_pp0_iter13_reg;
        icmp_ln166_3_reg_3870_pp0_iter15_reg <= icmp_ln166_3_reg_3870_pp0_iter14_reg;
        icmp_ln166_3_reg_3870_pp0_iter16_reg <= icmp_ln166_3_reg_3870_pp0_iter15_reg;
        icmp_ln166_3_reg_3870_pp0_iter2_reg <= icmp_ln166_3_reg_3870_pp0_iter1_reg;
        icmp_ln166_3_reg_3870_pp0_iter3_reg <= icmp_ln166_3_reg_3870_pp0_iter2_reg;
        icmp_ln166_3_reg_3870_pp0_iter4_reg <= icmp_ln166_3_reg_3870_pp0_iter3_reg;
        icmp_ln166_3_reg_3870_pp0_iter5_reg <= icmp_ln166_3_reg_3870_pp0_iter4_reg;
        icmp_ln166_3_reg_3870_pp0_iter6_reg <= icmp_ln166_3_reg_3870_pp0_iter5_reg;
        icmp_ln166_3_reg_3870_pp0_iter7_reg <= icmp_ln166_3_reg_3870_pp0_iter6_reg;
        icmp_ln166_3_reg_3870_pp0_iter8_reg <= icmp_ln166_3_reg_3870_pp0_iter7_reg;
        icmp_ln166_3_reg_3870_pp0_iter9_reg <= icmp_ln166_3_reg_3870_pp0_iter8_reg;
        icmp_ln166_5_reg_3875_pp0_iter10_reg <= icmp_ln166_5_reg_3875_pp0_iter9_reg;
        icmp_ln166_5_reg_3875_pp0_iter11_reg <= icmp_ln166_5_reg_3875_pp0_iter10_reg;
        icmp_ln166_5_reg_3875_pp0_iter12_reg <= icmp_ln166_5_reg_3875_pp0_iter11_reg;
        icmp_ln166_5_reg_3875_pp0_iter13_reg <= icmp_ln166_5_reg_3875_pp0_iter12_reg;
        icmp_ln166_5_reg_3875_pp0_iter14_reg <= icmp_ln166_5_reg_3875_pp0_iter13_reg;
        icmp_ln166_5_reg_3875_pp0_iter15_reg <= icmp_ln166_5_reg_3875_pp0_iter14_reg;
        icmp_ln166_5_reg_3875_pp0_iter16_reg <= icmp_ln166_5_reg_3875_pp0_iter15_reg;
        icmp_ln166_5_reg_3875_pp0_iter2_reg <= icmp_ln166_5_reg_3875_pp0_iter1_reg;
        icmp_ln166_5_reg_3875_pp0_iter3_reg <= icmp_ln166_5_reg_3875_pp0_iter2_reg;
        icmp_ln166_5_reg_3875_pp0_iter4_reg <= icmp_ln166_5_reg_3875_pp0_iter3_reg;
        icmp_ln166_5_reg_3875_pp0_iter5_reg <= icmp_ln166_5_reg_3875_pp0_iter4_reg;
        icmp_ln166_5_reg_3875_pp0_iter6_reg <= icmp_ln166_5_reg_3875_pp0_iter5_reg;
        icmp_ln166_5_reg_3875_pp0_iter7_reg <= icmp_ln166_5_reg_3875_pp0_iter6_reg;
        icmp_ln166_5_reg_3875_pp0_iter8_reg <= icmp_ln166_5_reg_3875_pp0_iter7_reg;
        icmp_ln166_5_reg_3875_pp0_iter9_reg <= icmp_ln166_5_reg_3875_pp0_iter8_reg;
        icmp_ln166_7_reg_3880_pp0_iter10_reg <= icmp_ln166_7_reg_3880_pp0_iter9_reg;
        icmp_ln166_7_reg_3880_pp0_iter11_reg <= icmp_ln166_7_reg_3880_pp0_iter10_reg;
        icmp_ln166_7_reg_3880_pp0_iter12_reg <= icmp_ln166_7_reg_3880_pp0_iter11_reg;
        icmp_ln166_7_reg_3880_pp0_iter13_reg <= icmp_ln166_7_reg_3880_pp0_iter12_reg;
        icmp_ln166_7_reg_3880_pp0_iter14_reg <= icmp_ln166_7_reg_3880_pp0_iter13_reg;
        icmp_ln166_7_reg_3880_pp0_iter15_reg <= icmp_ln166_7_reg_3880_pp0_iter14_reg;
        icmp_ln166_7_reg_3880_pp0_iter16_reg <= icmp_ln166_7_reg_3880_pp0_iter15_reg;
        icmp_ln166_7_reg_3880_pp0_iter2_reg <= icmp_ln166_7_reg_3880_pp0_iter1_reg;
        icmp_ln166_7_reg_3880_pp0_iter3_reg <= icmp_ln166_7_reg_3880_pp0_iter2_reg;
        icmp_ln166_7_reg_3880_pp0_iter4_reg <= icmp_ln166_7_reg_3880_pp0_iter3_reg;
        icmp_ln166_7_reg_3880_pp0_iter5_reg <= icmp_ln166_7_reg_3880_pp0_iter4_reg;
        icmp_ln166_7_reg_3880_pp0_iter6_reg <= icmp_ln166_7_reg_3880_pp0_iter5_reg;
        icmp_ln166_7_reg_3880_pp0_iter7_reg <= icmp_ln166_7_reg_3880_pp0_iter6_reg;
        icmp_ln166_7_reg_3880_pp0_iter8_reg <= icmp_ln166_7_reg_3880_pp0_iter7_reg;
        icmp_ln166_7_reg_3880_pp0_iter9_reg <= icmp_ln166_7_reg_3880_pp0_iter8_reg;
        icmp_ln166_9_reg_3885_pp0_iter10_reg <= icmp_ln166_9_reg_3885_pp0_iter9_reg;
        icmp_ln166_9_reg_3885_pp0_iter11_reg <= icmp_ln166_9_reg_3885_pp0_iter10_reg;
        icmp_ln166_9_reg_3885_pp0_iter12_reg <= icmp_ln166_9_reg_3885_pp0_iter11_reg;
        icmp_ln166_9_reg_3885_pp0_iter13_reg <= icmp_ln166_9_reg_3885_pp0_iter12_reg;
        icmp_ln166_9_reg_3885_pp0_iter14_reg <= icmp_ln166_9_reg_3885_pp0_iter13_reg;
        icmp_ln166_9_reg_3885_pp0_iter15_reg <= icmp_ln166_9_reg_3885_pp0_iter14_reg;
        icmp_ln166_9_reg_3885_pp0_iter16_reg <= icmp_ln166_9_reg_3885_pp0_iter15_reg;
        icmp_ln166_9_reg_3885_pp0_iter2_reg <= icmp_ln166_9_reg_3885_pp0_iter1_reg;
        icmp_ln166_9_reg_3885_pp0_iter3_reg <= icmp_ln166_9_reg_3885_pp0_iter2_reg;
        icmp_ln166_9_reg_3885_pp0_iter4_reg <= icmp_ln166_9_reg_3885_pp0_iter3_reg;
        icmp_ln166_9_reg_3885_pp0_iter5_reg <= icmp_ln166_9_reg_3885_pp0_iter4_reg;
        icmp_ln166_9_reg_3885_pp0_iter6_reg <= icmp_ln166_9_reg_3885_pp0_iter5_reg;
        icmp_ln166_9_reg_3885_pp0_iter7_reg <= icmp_ln166_9_reg_3885_pp0_iter6_reg;
        icmp_ln166_9_reg_3885_pp0_iter8_reg <= icmp_ln166_9_reg_3885_pp0_iter7_reg;
        icmp_ln166_9_reg_3885_pp0_iter9_reg <= icmp_ln166_9_reg_3885_pp0_iter8_reg;
        icmp_ln84_reg_3831_pp0_iter10_reg <= icmp_ln84_reg_3831_pp0_iter9_reg;
        icmp_ln84_reg_3831_pp0_iter11_reg <= icmp_ln84_reg_3831_pp0_iter10_reg;
        icmp_ln84_reg_3831_pp0_iter12_reg <= icmp_ln84_reg_3831_pp0_iter11_reg;
        icmp_ln84_reg_3831_pp0_iter13_reg <= icmp_ln84_reg_3831_pp0_iter12_reg;
        icmp_ln84_reg_3831_pp0_iter14_reg <= icmp_ln84_reg_3831_pp0_iter13_reg;
        icmp_ln84_reg_3831_pp0_iter15_reg <= icmp_ln84_reg_3831_pp0_iter14_reg;
        icmp_ln84_reg_3831_pp0_iter16_reg <= icmp_ln84_reg_3831_pp0_iter15_reg;
        icmp_ln84_reg_3831_pp0_iter2_reg <= icmp_ln84_reg_3831_pp0_iter1_reg;
        icmp_ln84_reg_3831_pp0_iter3_reg <= icmp_ln84_reg_3831_pp0_iter2_reg;
        icmp_ln84_reg_3831_pp0_iter4_reg <= icmp_ln84_reg_3831_pp0_iter3_reg;
        icmp_ln84_reg_3831_pp0_iter5_reg <= icmp_ln84_reg_3831_pp0_iter4_reg;
        icmp_ln84_reg_3831_pp0_iter6_reg <= icmp_ln84_reg_3831_pp0_iter5_reg;
        icmp_ln84_reg_3831_pp0_iter7_reg <= icmp_ln84_reg_3831_pp0_iter6_reg;
        icmp_ln84_reg_3831_pp0_iter8_reg <= icmp_ln84_reg_3831_pp0_iter7_reg;
        icmp_ln84_reg_3831_pp0_iter9_reg <= icmp_ln84_reg_3831_pp0_iter8_reg;
        inc280_i254_load_reg_3965 <= inc280_i254_fu_384;
        inc280_i_1256_load_reg_3970 <= inc280_i_1256_fu_388;
        inc280_i_2258_load_reg_3975 <= inc280_i_2258_fu_392;
        inc280_i_3260_load_reg_3980 <= inc280_i_3260_fu_396;
        inc280_i_4262_load_reg_3985 <= inc280_i_4262_fu_400;
        sum_tmp_62_reg_3990 <= sum_tmp_62_fu_2225_p3;
        sum_tmp_64_reg_3995 <= sum_tmp_64_fu_2255_p3;
        sum_tmp_67_reg_4000 <= sum_tmp_67_fu_2285_p3;
        sum_tmp_69_reg_4005 <= sum_tmp_69_fu_2315_p3;
        sum_tmp_70_reg_4010 <= sum_tmp_70_fu_2345_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln113_1_reg_3855 <= icmp_ln113_1_fu_1528_p2;
        icmp_ln113_reg_3845 <= icmp_ln113_fu_1501_p2;
        icmp_ln166_1_reg_3865 <= icmp_ln166_1_fu_1534_p2;
        icmp_ln166_1_reg_3865_pp0_iter1_reg <= icmp_ln166_1_reg_3865;
        icmp_ln166_3_reg_3870 <= icmp_ln166_3_fu_1550_p2;
        icmp_ln166_3_reg_3870_pp0_iter1_reg <= icmp_ln166_3_reg_3870;
        icmp_ln166_5_reg_3875 <= icmp_ln166_5_fu_1556_p2;
        icmp_ln166_5_reg_3875_pp0_iter1_reg <= icmp_ln166_5_reg_3875;
        icmp_ln166_7_reg_3880 <= icmp_ln166_7_fu_1562_p2;
        icmp_ln166_7_reg_3880_pp0_iter1_reg <= icmp_ln166_7_reg_3880;
        icmp_ln166_9_reg_3885 <= icmp_ln166_9_fu_1568_p2;
        icmp_ln166_9_reg_3885_pp0_iter1_reg <= icmp_ln166_9_reg_3885;
        icmp_ln84_reg_3831 <= icmp_ln84_fu_1451_p2;
        icmp_ln84_reg_3831_pp0_iter1_reg <= icmp_ln84_reg_3831;
        tmp_reg_3835 <= ap_sig_allocacmp_t[32'd12];
    end
end

always @ (*) begin
    if (((icmp_ln84_fu_1451_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd1))) begin
        ap_condition_exit_pp0_iter17_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter17_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter17_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_t = 13'd0;
    end else begin
        ap_sig_allocacmp_t = data_idx_fu_236;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_in_x_3_ce0_local = 1'b1;
    end else begin
        local_in_x_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_in_x_4_ce0_local = 1'b1;
    end else begin
        local_in_x_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_in_x_ce0_local = 1'b1;
    end else begin
        local_in_x_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter18 == 1'b1))) begin
        local_out_x_5_ce1_local = 1'b1;
    end else begin
        local_out_x_5_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln166_3_reg_4019) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter18 == 1'b1))) begin
        local_out_x_5_we1_local = 1'b1;
    end else begin
        local_out_x_5_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter18 == 1'b1))) begin
        local_out_x_6_ce1_local = 1'b1;
    end else begin
        local_out_x_6_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln166_5_reg_4023) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter18 == 1'b1))) begin
        local_out_x_6_we1_local = 1'b1;
    end else begin
        local_out_x_6_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter18 == 1'b1))) begin
        local_out_x_7_ce1_local = 1'b1;
    end else begin
        local_out_x_7_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln166_7_reg_4027) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter18 == 1'b1))) begin
        local_out_x_7_we1_local = 1'b1;
    end else begin
        local_out_x_7_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter18 == 1'b1))) begin
        local_out_x_8_ce1_local = 1'b1;
    end else begin
        local_out_x_8_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln166_9_reg_4031) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter18 == 1'b1))) begin
        local_out_x_8_we1_local = 1'b1;
    end else begin
        local_out_x_8_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter18 == 1'b1))) begin
        local_out_x_ce1_local = 1'b1;
    end else begin
        local_out_x_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln166_1_reg_4015) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter18 == 1'b1))) begin
        local_out_x_we1_local = 1'b1;
    end else begin
        local_out_x_we1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln112_1_fu_1507_p2 = ($signed(zext_ln84_1_fu_1468_p1) + $signed(14'd16382));

assign add_ln112_fu_1480_p2 = ($signed(zext_ln84_1_fu_1468_p1) + $signed(14'd16383));

assign add_ln169_1_fu_2416_p2 = (inc280_i_1256_fu_388 + 32'd1);

assign add_ln169_2_fu_2453_p2 = (inc280_i_2258_fu_392 + 32'd1);

assign add_ln169_3_fu_2490_p2 = (inc280_i_3260_fu_396 + 32'd1);

assign add_ln169_4_fu_2527_p2 = (inc280_i_4262_fu_400 + 32'd1);

assign add_ln169_fu_2379_p2 = (inc280_i254_fu_384 + 32'd1);

assign add_ln84_fu_1457_p2 = (ap_sig_allocacmp_t + 13'd1);

assign and_ln166_1_fu_2374_p2 = (icmp_ln166_1_reg_3865_pp0_iter16_reg & and_ln166_fu_2369_p2);

assign and_ln166_2_fu_2406_p2 = (icmp_ln166_4_fu_2400_p2 & icmp);

assign and_ln166_3_fu_2411_p2 = (icmp_ln166_3_reg_3870_pp0_iter16_reg & and_ln166_2_fu_2406_p2);

assign and_ln166_4_fu_2443_p2 = (icmp_ln166_6_fu_2437_p2 & cmp261_i_2);

assign and_ln166_5_fu_2448_p2 = (icmp_ln166_5_reg_3875_pp0_iter16_reg & and_ln166_4_fu_2443_p2);

assign and_ln166_6_fu_2480_p2 = (icmp_ln166_8_fu_2474_p2 & icmp42);

assign and_ln166_7_fu_2485_p2 = (icmp_ln166_7_reg_3880_pp0_iter16_reg & and_ln166_6_fu_2480_p2);

assign and_ln166_8_fu_2517_p2 = (icmp_ln166_10_fu_2511_p2 & cmp261_i_4);

assign and_ln166_9_fu_2522_p2 = (icmp_ln166_9_reg_3885_pp0_iter16_reg & and_ln166_8_fu_2517_p2);

assign and_ln166_fu_2369_p2 = (icmp_ln166_2_fu_2363_p2 & icmp_ln166);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp297 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp298 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp299 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp300 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp301 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp302 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp303 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp304 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp305 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp306 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp307 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp308 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp309 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp310 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp311 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_3837 = ((1'd1 == and_ln166_1_fu_2374_p2) & (ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0));
end

always @ (*) begin
    ap_condition_3841 = ((1'd1 == and_ln166_3_fu_2411_p2) & (ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0));
end

always @ (*) begin
    ap_condition_3845 = ((1'd1 == and_ln166_5_fu_2448_p2) & (ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0));
end

always @ (*) begin
    ap_condition_3849 = ((1'd1 == and_ln166_7_fu_2485_p2) & (ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0));
end

always @ (*) begin
    ap_condition_3853 = ((1'd1 == and_ln166_9_fu_2522_p2) & (ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln84_reg_3831_pp0_iter16_reg == 1'd0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign empty_47_fu_1646_p3 = ((icmp_ln113_reg_3845[0:0] == 1'b1) ? local_in_x_3_q0 : 64'd0);

assign empty_48_fu_1653_p3 = ((icmp_ln113_1_reg_3855[0:0] == 1'b1) ? local_in_x_4_q0 : 64'd0);

assign empty_fu_1639_p3 = ((tmp_reg_3835[0:0] == 1'b1) ? 64'd0 : local_in_x_q0);

assign icmp_ln113_1_fu_1528_p2 = ((tmp_2_fu_1518_p4 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln113_fu_1501_p2 = ((tmp_1_fu_1491_p4 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln155_10_fu_2209_p2 = ((sum_tmp_60_fu_2203_p2 < mod_p_reload) ? 1'b1 : 1'b0);

assign icmp_ln155_11_fu_2239_p2 = ((sum_tmp_63_fu_2233_p2 < mod_p_1_reload) ? 1'b1 : 1'b0);

assign icmp_ln155_12_fu_2269_p2 = ((sum_tmp_65_fu_2263_p2 < mod_p_2_reload) ? 1'b1 : 1'b0);

assign icmp_ln155_13_fu_2299_p2 = ((sum_tmp_68_fu_2293_p2 < p_reload147) ? 1'b1 : 1'b0);

assign icmp_ln155_14_fu_2329_p2 = ((sum_tmp_fu_2323_p2 < mod_p_4_reload) ? 1'b1 : 1'b0);

assign icmp_ln155_1_fu_1957_p2 = ((sum_tmp_2_fu_304 < mod_p_1_reload) ? 1'b1 : 1'b0);

assign icmp_ln155_2_fu_1981_p2 = ((sum_tmp_3_fu_308 < mod_p_2_reload) ? 1'b1 : 1'b0);

assign icmp_ln155_3_fu_2005_p2 = ((sum_tmp_4_fu_312 < p_reload147) ? 1'b1 : 1'b0);

assign icmp_ln155_4_fu_2029_p2 = ((sum_tmp_5_fu_316 < mod_p_4_reload) ? 1'b1 : 1'b0);

assign icmp_ln155_5_fu_2059_p2 = ((sum_tmp_47_fu_2053_p2 < mod_p_reload) ? 1'b1 : 1'b0);

assign icmp_ln155_6_fu_2089_p2 = ((sum_tmp_50_fu_2083_p2 < mod_p_1_reload) ? 1'b1 : 1'b0);

assign icmp_ln155_7_fu_2119_p2 = ((sum_tmp_52_fu_2113_p2 < mod_p_2_reload) ? 1'b1 : 1'b0);

assign icmp_ln155_8_fu_2149_p2 = ((sum_tmp_55_fu_2143_p2 < p_reload147) ? 1'b1 : 1'b0);

assign icmp_ln155_9_fu_2179_p2 = ((sum_tmp_57_fu_2173_p2 < mod_p_4_reload) ? 1'b1 : 1'b0);

assign icmp_ln155_fu_1933_p2 = ((sum_tmp_1_fu_300 < mod_p_reload) ? 1'b1 : 1'b0);

assign icmp_ln166_10_fu_2511_p2 = (($signed(tmp_8_fu_2501_p4) < $signed(20'd1)) ? 1'b1 : 1'b0);

assign icmp_ln166_1_fu_1534_p2 = ((ap_sig_allocacmp_t > 13'd6) ? 1'b1 : 1'b0);

assign icmp_ln166_2_fu_2363_p2 = (($signed(tmp_3_fu_2353_p4) < $signed(20'd1)) ? 1'b1 : 1'b0);

assign icmp_ln166_3_fu_1550_p2 = ((tmp_4_fu_1540_p4 != 10'd0) ? 1'b1 : 1'b0);

assign icmp_ln166_4_fu_2400_p2 = (($signed(tmp_5_fu_2390_p4) < $signed(20'd1)) ? 1'b1 : 1'b0);

assign icmp_ln166_5_fu_1556_p2 = ((ap_sig_allocacmp_t > 13'd8) ? 1'b1 : 1'b0);

assign icmp_ln166_6_fu_2437_p2 = (($signed(tmp_6_fu_2427_p4) < $signed(20'd1)) ? 1'b1 : 1'b0);

assign icmp_ln166_7_fu_1562_p2 = ((ap_sig_allocacmp_t > 13'd9) ? 1'b1 : 1'b0);

assign icmp_ln166_8_fu_2474_p2 = (($signed(tmp_7_fu_2464_p4) < $signed(20'd1)) ? 1'b1 : 1'b0);

assign icmp_ln166_9_fu_1568_p2 = ((ap_sig_allocacmp_t > 13'd10) ? 1'b1 : 1'b0);

assign icmp_ln84_fu_1451_p2 = ((ap_sig_allocacmp_t == 13'd4107) ? 1'b1 : 1'b0);

assign local_in_x_3_address0 = zext_ln113_fu_1486_p1;

assign local_in_x_3_ce0 = local_in_x_3_ce0_local;

assign local_in_x_4_address0 = zext_ln113_1_fu_1513_p1;

assign local_in_x_4_ce0 = local_in_x_4_ce0_local;

assign local_in_x_address0 = zext_ln84_fu_1463_p1;

assign local_in_x_ce0 = local_in_x_ce0_local;

assign local_out_x_5_address1 = zext_ln168_1_fu_2937_p1;

assign local_out_x_5_ce1 = local_out_x_5_ce1_local;

assign local_out_x_5_d1 = sum_tmp_64_reg_3995;

assign local_out_x_5_we1 = local_out_x_5_we1_local;

assign local_out_x_6_address1 = zext_ln168_2_fu_2941_p1;

assign local_out_x_6_ce1 = local_out_x_6_ce1_local;

assign local_out_x_6_d1 = sum_tmp_67_reg_4000;

assign local_out_x_6_we1 = local_out_x_6_we1_local;

assign local_out_x_7_address1 = zext_ln168_3_fu_2945_p1;

assign local_out_x_7_ce1 = local_out_x_7_ce1_local;

assign local_out_x_7_d1 = sum_tmp_69_reg_4005;

assign local_out_x_7_we1 = local_out_x_7_we1_local;

assign local_out_x_8_address1 = zext_ln168_4_fu_2949_p1;

assign local_out_x_8_ce1 = local_out_x_8_ce1_local;

assign local_out_x_8_d1 = sum_tmp_70_reg_4010;

assign local_out_x_8_we1 = local_out_x_8_we1_local;

assign local_out_x_address1 = zext_ln168_fu_2933_p1;

assign local_out_x_ce1 = local_out_x_ce1_local;

assign local_out_x_d1 = sum_tmp_62_reg_3990;

assign local_out_x_we1 = local_out_x_we1_local;

assign sub_ln155_11_fu_2250_p2 = (sum_tmp_63_fu_2233_p2 - mod_p_1_reload);

assign sub_ln155_13_fu_2310_p2 = (sum_tmp_68_fu_2293_p2 - p_reload147);

assign sub_ln155_1_fu_1968_p2 = (sum_tmp_2_fu_304 - mod_p_1_reload);

assign sub_ln155_3_fu_2016_p2 = (sum_tmp_4_fu_312 - p_reload147);

assign sub_ln155_6_fu_2100_p2 = (sum_tmp_50_fu_2083_p2 - mod_p_1_reload);

assign sub_ln155_8_fu_2160_p2 = (sum_tmp_55_fu_2143_p2 - p_reload147);

assign sum_tmp_37_fu_2340_p2 = (sum_tmp_fu_2323_p2 - mod_p_4_reload);

assign sum_tmp_39_fu_1944_p2 = (sum_tmp_1_fu_300 - mod_p_reload);

assign sum_tmp_40_fu_1949_p3 = ((xor_ln155_fu_1938_p2[0:0] == 1'b1) ? sum_tmp_39_fu_1944_p2 : sum_tmp_1_fu_300);

assign sum_tmp_41_fu_1973_p3 = ((xor_ln155_1_fu_1962_p2[0:0] == 1'b1) ? sub_ln155_1_fu_1968_p2 : sum_tmp_2_fu_304);

assign sum_tmp_42_fu_1992_p2 = (sum_tmp_3_fu_308 - mod_p_2_reload);

assign sum_tmp_43_fu_1997_p3 = ((xor_ln155_2_fu_1986_p2[0:0] == 1'b1) ? sum_tmp_42_fu_1992_p2 : sum_tmp_3_fu_308);

assign sum_tmp_44_fu_2021_p3 = ((xor_ln155_3_fu_2010_p2[0:0] == 1'b1) ? sub_ln155_3_fu_2016_p2 : sum_tmp_4_fu_312);

assign sum_tmp_45_fu_2040_p2 = (sum_tmp_5_fu_316 - mod_p_4_reload);

assign sum_tmp_46_fu_2045_p3 = ((xor_ln155_4_fu_2034_p2[0:0] == 1'b1) ? sum_tmp_45_fu_2040_p2 : sum_tmp_5_fu_316);

assign sum_tmp_47_fu_2053_p2 = (sum_in_fu_196 + delayed_prod_fu_320);

assign sum_tmp_48_fu_2070_p2 = (sum_tmp_47_fu_2053_p2 - mod_p_reload);

assign sum_tmp_49_fu_2075_p3 = ((xor_ln155_5_fu_2064_p2[0:0] == 1'b1) ? sum_tmp_48_fu_2070_p2 : sum_tmp_47_fu_2053_p2);

assign sum_tmp_50_fu_2083_p2 = (sum_in_1_fu_204 + delayed_prod_1_fu_324);

assign sum_tmp_51_fu_2105_p3 = ((xor_ln155_6_fu_2094_p2[0:0] == 1'b1) ? sub_ln155_6_fu_2100_p2 : sum_tmp_50_fu_2083_p2);

assign sum_tmp_52_fu_2113_p2 = (sum_in_2_fu_212 + delayed_prod_2_fu_328);

assign sum_tmp_53_fu_2130_p2 = (sum_tmp_52_fu_2113_p2 - mod_p_2_reload);

assign sum_tmp_54_fu_2135_p3 = ((xor_ln155_7_fu_2124_p2[0:0] == 1'b1) ? sum_tmp_53_fu_2130_p2 : sum_tmp_52_fu_2113_p2);

assign sum_tmp_55_fu_2143_p2 = (sum_in_3_fu_220 + delayed_prod_3_fu_332);

assign sum_tmp_56_fu_2165_p3 = ((xor_ln155_8_fu_2154_p2[0:0] == 1'b1) ? sub_ln155_8_fu_2160_p2 : sum_tmp_55_fu_2143_p2);

assign sum_tmp_57_fu_2173_p2 = (sum_in_4_fu_228 + delayed_prod_4_fu_336);

assign sum_tmp_58_fu_2190_p2 = (sum_tmp_57_fu_2173_p2 - mod_p_4_reload);

assign sum_tmp_59_fu_2195_p3 = ((xor_ln155_9_fu_2184_p2[0:0] == 1'b1) ? sum_tmp_58_fu_2190_p2 : sum_tmp_57_fu_2173_p2);

assign sum_tmp_60_fu_2203_p2 = (sum_in_5_fu_200 + delayed_prod_5_fu_340);

assign sum_tmp_61_fu_2220_p2 = (sum_tmp_60_fu_2203_p2 - mod_p_reload);

assign sum_tmp_62_fu_2225_p3 = ((xor_ln155_10_fu_2214_p2[0:0] == 1'b1) ? sum_tmp_61_fu_2220_p2 : sum_tmp_60_fu_2203_p2);

assign sum_tmp_63_fu_2233_p2 = (sum_in_6_fu_208 + delayed_prod_6_fu_344);

assign sum_tmp_64_fu_2255_p3 = ((xor_ln155_11_fu_2244_p2[0:0] == 1'b1) ? sub_ln155_11_fu_2250_p2 : sum_tmp_63_fu_2233_p2);

assign sum_tmp_65_fu_2263_p2 = (sum_in_7_fu_216 + delayed_prod_7_fu_348);

assign sum_tmp_66_fu_2280_p2 = (sum_tmp_65_fu_2263_p2 - mod_p_2_reload);

assign sum_tmp_67_fu_2285_p3 = ((xor_ln155_12_fu_2274_p2[0:0] == 1'b1) ? sum_tmp_66_fu_2280_p2 : sum_tmp_65_fu_2263_p2);

assign sum_tmp_68_fu_2293_p2 = (sum_in_8_fu_224 + delayed_prod_8_fu_352);

assign sum_tmp_69_fu_2315_p3 = ((xor_ln155_13_fu_2304_p2[0:0] == 1'b1) ? sub_ln155_13_fu_2310_p2 : sum_tmp_68_fu_2293_p2);

assign sum_tmp_70_fu_2345_p3 = ((xor_ln155_14_fu_2334_p2[0:0] == 1'b1) ? sum_tmp_37_fu_2340_p2 : sum_tmp_fu_2323_p2);

assign sum_tmp_fu_2323_p2 = (sum_in_9_fu_232 + delayed_prod_9_fu_356);

assign tmp_1_fu_1491_p4 = {{add_ln112_fu_1480_p2[13:12]}};

assign tmp_2_fu_1518_p4 = {{add_ln112_1_fu_1507_p2[13:12]}};

assign tmp_3_fu_2353_p4 = {{inc280_i254_fu_384[31:12]}};

assign tmp_4_fu_1540_p4 = {{ap_sig_allocacmp_t[12:3]}};

assign tmp_5_fu_2390_p4 = {{inc280_i_1256_fu_388[31:12]}};

assign tmp_6_fu_2427_p4 = {{inc280_i_2258_fu_392[31:12]}};

assign tmp_7_fu_2464_p4 = {{inc280_i_3260_fu_396[31:12]}};

assign tmp_8_fu_2501_p4 = {{inc280_i_4262_fu_400[31:12]}};

assign xor_ln155_10_fu_2214_p2 = (icmp_ln155_10_fu_2209_p2 ^ 1'd1);

assign xor_ln155_11_fu_2244_p2 = (icmp_ln155_11_fu_2239_p2 ^ 1'd1);

assign xor_ln155_12_fu_2274_p2 = (icmp_ln155_12_fu_2269_p2 ^ 1'd1);

assign xor_ln155_13_fu_2304_p2 = (icmp_ln155_13_fu_2299_p2 ^ 1'd1);

assign xor_ln155_14_fu_2334_p2 = (icmp_ln155_14_fu_2329_p2 ^ 1'd1);

assign xor_ln155_1_fu_1962_p2 = (icmp_ln155_1_fu_1957_p2 ^ 1'd1);

assign xor_ln155_2_fu_1986_p2 = (icmp_ln155_2_fu_1981_p2 ^ 1'd1);

assign xor_ln155_3_fu_2010_p2 = (icmp_ln155_3_fu_2005_p2 ^ 1'd1);

assign xor_ln155_4_fu_2034_p2 = (icmp_ln155_4_fu_2029_p2 ^ 1'd1);

assign xor_ln155_5_fu_2064_p2 = (icmp_ln155_5_fu_2059_p2 ^ 1'd1);

assign xor_ln155_6_fu_2094_p2 = (icmp_ln155_6_fu_2089_p2 ^ 1'd1);

assign xor_ln155_7_fu_2124_p2 = (icmp_ln155_7_fu_2119_p2 ^ 1'd1);

assign xor_ln155_8_fu_2154_p2 = (icmp_ln155_8_fu_2149_p2 ^ 1'd1);

assign xor_ln155_9_fu_2184_p2 = (icmp_ln155_9_fu_2179_p2 ^ 1'd1);

assign xor_ln155_fu_1938_p2 = (icmp_ln155_fu_1933_p2 ^ 1'd1);

assign zext_ln113_1_fu_1513_p1 = add_ln112_1_fu_1507_p2;

assign zext_ln113_fu_1486_p1 = add_ln112_fu_1480_p2;

assign zext_ln168_1_fu_2937_p1 = inc280_i_1256_load_reg_3970;

assign zext_ln168_2_fu_2941_p1 = inc280_i_2258_load_reg_3975;

assign zext_ln168_3_fu_2945_p1 = inc280_i_3260_load_reg_3980;

assign zext_ln168_4_fu_2949_p1 = inc280_i_4262_load_reg_3985;

assign zext_ln168_fu_2933_p1 = inc280_i254_load_reg_3965;

assign zext_ln84_1_fu_1468_p1 = ap_sig_allocacmp_t;

assign zext_ln84_fu_1463_p1 = ap_sig_allocacmp_t;

endmodule //Compute_BConv_Compute_BConv_Pipeline_Systolic_Loop
