#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("in_x_address0", 15, hls_out, 0, "ap_memory", "mem_address", 1),
	Port_Property("in_x_ce0", 1, hls_out, 0, "ap_memory", "mem_ce", 1),
	Port_Property("in_x_we0", 1, hls_out, 0, "ap_memory", "mem_we", 1),
	Port_Property("in_x_d0", 64, hls_out, 0, "ap_memory", "mem_din", 1),
	Port_Property("in_x_q0", 64, hls_in, 0, "ap_memory", "mem_dout", 1),
	Port_Property("in_w_address0", 4, hls_out, 1, "ap_memory", "mem_address", 1),
	Port_Property("in_w_ce0", 1, hls_out, 1, "ap_memory", "mem_ce", 1),
	Port_Property("in_w_q0", 64, hls_in, 1, "ap_memory", "mem_dout", 1),
	Port_Property("out_mod_address0", 3, hls_out, 2, "ap_memory", "mem_address", 1),
	Port_Property("out_mod_ce0", 1, hls_out, 2, "ap_memory", "mem_ce", 1),
	Port_Property("out_mod_q0", 64, hls_in, 2, "ap_memory", "mem_dout", 1),
	Port_Property("out_k_half_address0", 3, hls_out, 3, "ap_memory", "mem_address", 1),
	Port_Property("out_k_half_ce0", 1, hls_out, 3, "ap_memory", "mem_ce", 1),
	Port_Property("out_k_half_q0", 64, hls_in, 3, "ap_memory", "mem_dout", 1),
	Port_Property("out_m_barrett_address0", 3, hls_out, 4, "ap_memory", "mem_address", 1),
	Port_Property("out_m_barrett_ce0", 1, hls_out, 4, "ap_memory", "mem_ce", 1),
	Port_Property("out_m_barrett_q0", 64, hls_in, 4, "ap_memory", "mem_dout", 1),
	Port_Property("sizeP", 32, hls_in, 5, "ap_none", "in_data", 1),
};
const char* HLS_Design_Meta::dut_name = "Compute_BConv";
